/**
 * tree.js — Veliatychi family tree visualiser
 *
 * Data is loaded from JSON files in data/ (generated by export.py).
 * Navigation is driven by URL hash: #<person_id>
 */

'use strict';

// ── Configuration ────────────────────────────────────────────
const CONFIG = {
  homeId:   11083,      // default person on first load — change to suit
  dataDir:  'data/',
  dataFiles: ['si', 'parents', 'children', 'marriages', 'places', 'nums', 'births', 'deaths'],
};

// ── Layout constants ─────────────────────────────────────────
const NODE_W   = 152;  // node width (px)
const NODE_H   = 88;   // node min-height (px) — used for spacing only
const GAP_X    = 20;   // horizontal gap between sibling nodes
const GAP_Y    = 80;   // vertical gap between generation rows
const ROW_H    = NODE_H + GAP_Y;
const SP_GAP   = 32;   // gap between root node edge and spouse node edge
const FAM_GAP  = 40;   // gap between children groups of different spouses
const STAGGER  = 22;   // vertical stagger between family drop bars (px)
const LABEL_W  = 90;   // left margin reserved for generation labels

// Derived row Y positions (relative to canvas top)
const Y_GGP  = 24;                    // great-grandparents
const Y_GP   = Y_GGP + ROW_H;        // grandparents
const Y_PAR  = Y_GP  + ROW_H;        // parents + root + spouses
const Y_CH   = Y_PAR + ROW_H;        // children
const Y_GCH  = Y_CH  + ROW_H;        // grandchildren (label only)

const HLINE_Y    = Y_PAR + Math.round(NODE_H / 2);  // marriage line Y
const BASE_DROP_Y = Y_PAR + NODE_H + 36;             // top of first child drop bar

// ── Global data store ─────────────────────────────────────────
// Populated by loadData(). Short names match JSON file names.
let SI; // search index: [[id, sex, given, patronymic, surname, maiden, birth_year], ...]
let PA; // parents:      {child_id: [father_id, mother_id]}
let CH; // children:     {parent_id: [child_id, ...]}
let MA; // marriages:    {person_id: [[spouse_id, [y,m,d], [child_ids]], ...]}
let PL; // places:       {person_id: "place name"}
let NU; // nums:         {person_id: integer}
let BI; // births:       {person_id: [y, m, d]}
let DE; // deaths:       {person_id: [y, m, d]}

let currentRootId = null;
let currentMode = 'ancestors';

// ── Bootstrap ────────────────────────────────────────────────
(async function init() {
  await loadData();
  const startId = parseInt(location.hash.slice(1)) || CONFIG.homeId;
  renderTree(buildTree(startId));
  initSearch();
  initUI();
})();

// ── Data loading ─────────────────────────────────────────────
async function loadData() {
  const fill = document.getElementById('loading-fill');
  const msg  = document.getElementById('loading-msg');

  try {
    const results = {};
    for (let i = 0; i < CONFIG.dataFiles.length; i++) {
      const name = CONFIG.dataFiles[i];
      msg.textContent = `Загрузка ${name}…`;
      const resp = await fetch(CONFIG.dataDir + name + '.json');
      if (!resp.ok) throw new Error(`Failed to fetch ${name}.json (HTTP ${resp.status})`);
      results[name] = await resp.json();
      fill.style.width = Math.round((i + 1) / CONFIG.dataFiles.length * 100) + '%';
    }
    ({ si: SI, parents: PA, children: CH, marriages: MA,
       places: PL, nums: NU, births: BI, deaths: DE } = results);
    document.getElementById('loading').style.display = 'none';

  } catch (err) {
    document.getElementById('loading').style.display = 'none';
    document.getElementById('err-msg').textContent =
      err.message + '\n\nПераканайцеся, што файлы JSON знаходзяцца ў папцы data/. Запусціце export.py для іх стварэння.';
    document.getElementById('err').style.display = 'flex';
    throw err; // stop execution
  }
}

// ── Data helpers ─────────────────────────────────────────────

/** Format a [year, month, day] date tuple as dd.mm.yyyy */
function formatDate(d) {
  if (!d) return '?';
  const [y, m, dd] = d;
  if (!y)  return '?';
  if (!m)  return String(y);
  const pad = n => n ? String(n).padStart(2, '0') : '??';
  if (!dd) return `??.${pad(m)}.${y}`;
  return `${pad(dd)}.${pad(m)}.${y}`;
}

/** Build a display name: Surname (Maiden) Given Patronymic */
function formatName(given, patronymic, surname, maiden) {
  const surnamePart = surname
    ? (maiden && maiden !== surname ? `${surname} (${maiden})` : surname)
    : (maiden || null);
  return [surnamePart, given, patronymic].filter(Boolean).join(' ');
}

/** Build a person object from the data store */
/** Build a person object from the data store */
function buildPerson(id) {
  if (!id) return null;
  const r = SI.find(x => x[0] == id);
  if (!r && !BI[id] && !DE[id]) return null;
  return {
    id,
    sex:        r ? r[1] : 0,
    given:      r ? r[2] : null,
    patronymic: r ? r[3] : null,
    surname:    r ? r[4] : null,
    maiden:     r ? r[5] : null,
    birth:      BI[id] || null,
    death:      DE[id] || null,
    place:      PL[id] || null,
    num:        NU[id] ?? null,
  };
}

/**
 * Recursively build an ancestor subtree node.
 * Each node: { person, father, mother } (father/mother are ancestor nodes or null).
 */
function buildAncestorNode(id, seen = new Set()) {
  if (!id) return null;
  const key = String(id);
  if (seen.has(key)) return null;
  const person = buildPerson(id);
  if (!person) return null;
  const nextSeen = new Set(seen);
  nextSeen.add(key);
  const [fatherId, motherId] = PA[id] || [null, null];
  return {
    person,
    father: buildAncestorNode(fatherId, nextSeen),
    mother: buildAncestorNode(motherId, nextSeen),
  };
}

/** Compute the minimum horizontal slot width needed for an ancestor subtree. */
function slotWidth(node) {
  if (!node) return 0;
  const fw = slotWidth(node.father);
  const mw = slotWidth(node.mother);
  if (!fw && !mw) return NODE_W;
  if (!fw) return Math.max(NODE_W, mw);
  if (!mw) return Math.max(NODE_W, fw);
  return Math.max(NODE_W, fw + GAP_X + mw);
}

/**
 * Assign cx (horizontal centre) to every ancestor node, top-down.
 * Returns flat array of { person, cx, depth } for all ancestors.
 * depth=0 is the root, depth=1 is parents, etc.
 */
function assignAncestorPositions(node, cx, depth, results = []) {
  if (!node) return results;
  results.push({ person: node.person, cx, depth });
  const fw = slotWidth(node.father);
  const mw = slotWidth(node.mother);
  if (node.father && node.mother) {
    // Two parents: place symmetrically left (father) and right (mother)
    const totalW = fw + GAP_X + mw;
    assignAncestorPositions(node.father, cx - totalW/2 + fw/2,  depth + 1, results);
    assignAncestorPositions(node.mother, cx + totalW/2 - mw/2, depth + 1, results);
  } else if (node.father) {
    // Single parent: directly above
    assignAncestorPositions(node.father, cx, depth + 1, results);
  } else if (node.mother) {
    assignAncestorPositions(node.mother, cx, depth + 1, results);
  }
  return results;
}

/** Build the full tree data structure centred on rootId. */
function buildTree(rootId) {
  const root = buildPerson(rootId);
  if (!root) return null;

  const [fatherId, motherId] = PA[rootId] || [null, null];
  const ancestorTree = {
    person: root,
    father: buildAncestorNode(fatherId, new Set([String(rootId)])),
    mother: buildAncestorNode(motherId, new Set([String(rootId)])),
  };

  const families = (MA[rootId] || []).map(([spouseId, marriageDate, childIds]) => {
    // childIds from MA is the per-couple list; fall back to all children if empty
    const children = (childIds && childIds.length)
      ? childIds.map(buildPerson).filter(Boolean)
      : [];
    return {
      spouse:   buildPerson(spouseId),
      date:     marriageDate,
      children,
    };
  });

  // Fallback: no marriage records at all — use CH map
  if (!families.length) {
    const ch = (CH[rootId] || []).map(buildPerson).filter(Boolean);
    if (ch.length) families.push({ spouse: null, date: null, children: ch });
  }

  // Any children not accounted for in MA get their own anonymous family
  const allKnownChildren = new Set(families.flatMap(f => f.children.map(c => c.id)));
  const chChildren = (CH[rootId] || []).map(buildPerson).filter(Boolean);
  const unknownChildren = chChildren.filter(c => !allKnownChildren.has(c.id));
  if (unknownChildren.length) {
    families.push({ spouse: null, date: null, children: unknownChildren });
  }

  // Remove families that have neither spouse nor children (nothing to show)
  const validFamilies = families.filter(f => f.spouse || f.children.length);

  validFamilies.forEach(fam => {
    fam.children.sort((a, b) =>
      ((a.birth && a.birth[0]) || 9999) - ((b.birth && b.birth[0]) || 9999)
    );
  });

  return { ancestorTree, families: validFamilies };
}

function birthYear(person) {
  if (!person) return 9999;
  if (person.birth && person.birth[0]) return person.birth[0];
  const r = SI.find(x => x[0] == person.id);
  return (r && r[6]) || 9999;
}

function buildFamilyGroups(personId) {
  const families = (MA[personId] || []).map(([spouseId, marriageDate, childIds]) => {
    const children = (childIds && childIds.length)
      ? childIds.map(buildPerson).filter(Boolean)
      : [];
    return {
      spouse: buildPerson(spouseId),
      date: marriageDate,
      children,
    };
  });

  if (!families.length) {
    const ch = (CH[personId] || []).map(buildPerson).filter(Boolean);
    if (ch.length) families.push({ spouse: null, date: null, children: ch });
  }

  const allKnownChildren = new Set(families.flatMap(f => f.children.map(c => c.id)));
  const chChildren = (CH[personId] || []).map(buildPerson).filter(Boolean);
  const unknownChildren = chChildren.filter(c => !allKnownChildren.has(c.id));
  if (unknownChildren.length) {
    families.push({ spouse: null, date: null, children: unknownChildren });
  }

  const validFamilies = families.filter(f => f.spouse || f.children.length);
  validFamilies.forEach(fam => {
    fam.children.sort((a, b) => birthYear(a) - birthYear(b));
  });

  return validFamilies;
}

const DESCENDANT_LAYOUT_CACHE = new Map();

function computeDescendantDepth(personId) {
  let depth = 0;
  let queue = [personId];
  while (queue.length) {
    const next = [];
    for (const id of queue) {
      const families = buildFamilyGroups(id);
      families.forEach(f => {
        f.children.forEach(c => next.push(c.id));
      });
    }
    if (!next.length) break;
    depth += 1;
    queue = next;
  }
  return depth;
}

function computeDescendantLayout(personId) {
  if (DESCENDANT_LAYOUT_CACHE.has(personId)) return DESCENDANT_LAYOUT_CACHE.get(personId);

  const families = buildFamilyGroups(personId);
  if (!families.length) {
    const layout = {
      width: NODE_W,
      rootOffset: NODE_W / 2,
    };
    DESCENDANT_LAYOUT_CACHE.set(personId, layout);
    return layout;
  }

  const orderedFams = families.length > 1 ? [families[0], ...families.slice(1)] : families;
  const leftFams = families.length > 1 ? [families[0]] : [];
  const rightFams = families.length > 1 ? families.slice(1) : families;
  const leftSpouseOffsets = leftFams.map((_, i) => -(NODE_W / 2 + SP_GAP + NODE_W / 2 + i * (NODE_W + SP_GAP)));
  const rightSpouseOffsets = rightFams.map((_, i) => NODE_W / 2 + SP_GAP + NODE_W / 2 + i * (NODE_W + SP_GAP));
  const anchorOffsets = [...leftSpouseOffsets.map(o => o / 2), ...rightSpouseOffsets.map(o => o / 2)];

  const familyBlocks = orderedFams.map((fam, fi) => {
    const childLayouts = fam.children.map(c => computeDescendantLayout(c.id));
    const childrenWidth = childLayouts.length
      ? childLayouts.reduce((sum, l) => sum + l.width, 0) + (childLayouts.length - 1) * GAP_X
      : NODE_W;
    const spouseSpan = fam.spouse ? NODE_W + SP_GAP + NODE_W : NODE_W;
    const blockWidth = Math.max(childrenWidth, spouseSpan, NODE_W);
    return {
      fam,
      fi,
      children: fam.children,
      childLayouts,
      childrenWidth,
      blockWidth,
      hasSpouse: !!fam.spouse,
    };
  });

  const totalFamilyWidth = familyBlocks.length
    ? familyBlocks.reduce((sum, b) => sum + b.blockWidth, 0) + (familyBlocks.length - 1) * FAM_GAP
    : NODE_W;

  const anchorOffset = familyBlocks.length === 1 && familyBlocks[0].hasSpouse
    ? anchorOffsets[familyBlocks[0].fi]
    : 0;
  const childrenStart = anchorOffset - totalFamilyWidth / 2;
  let cursor = childrenStart;
  let minX = -NODE_W / 2;
  let maxX = NODE_W / 2;

  leftSpouseOffsets.forEach(offset => {
    minX = Math.min(minX, offset - NODE_W / 2);
    maxX = Math.max(maxX, offset + NODE_W / 2);
  });
  rightSpouseOffsets.forEach(offset => {
    minX = Math.min(minX, offset - NODE_W / 2);
    maxX = Math.max(maxX, offset + NODE_W / 2);
  });

  familyBlocks.forEach(block => {
    block.left = cursor;
    minX = Math.min(minX, cursor);
    maxX = Math.max(maxX, cursor + block.blockWidth);
    cursor += block.blockWidth + FAM_GAP;
  });

  const width = maxX - minX;
  const rootOffset = -minX;

  const layout = { width, rootOffset };
  DESCENDANT_LAYOUT_CACHE.set(personId, layout);
  return layout;
}

function computeDescendantWidth(personId) {
  return computeDescendantLayout(personId).width;
}

// ── Layout helpers ───────────────────────────────────────────

/** X centre of a node placed at left edge x */
const nodeCx = x => x + NODE_W / 2;

/** Y bottom of a node placed at top edge y */
const nodeBot = y => y + NODE_H;

// ── SVG helpers ──────────────────────────────────────────────

function svgEl(tag, attrs) {
  const el = document.createElementNS('http://www.w3.org/2000/svg', tag);
  for (const [k, v] of Object.entries(attrs)) el.setAttribute(k, v);
  return el;
}

function drawLine(svg, x1, y1, x2, y2, stroke, dashed = false) {
  const attrs = { x1, y1, x2, y2, stroke, 'stroke-width': '1.5' };
  if (dashed) attrs['stroke-dasharray'] = '5,4';
  svg.appendChild(svgEl('line', attrs));
}

function drawBar(svg, cx1, cx2, y, stroke) {
  drawLine(svg, Math.min(cx1, cx2), y, Math.max(cx1, cx2), y, stroke);
}

// ── Node DOM helpers ─────────────────────────────────────────

function createNode(person, x, y, isRoot = false) {
  if (!person) return null;
  const name = formatName(person.given, person.patronymic, person.surname, person.maiden)
             || `Асоба #${person.id}`;
  const dates = (person.birth || person.death)
    ? `${formatDate(person.birth)} — ${formatDate(person.death)}` : '';
  const div = document.createElement('div');
  div.className = ['node',
    person.sex === 1 ? 'sex-m' : person.sex === 2 ? 'sex-f' : '',
    isRoot ? 'is-root' : ''].filter(Boolean).join(' ');
  div.style.cssText = `left:${x}px;top:${y}px`;
  div.dataset.id = person.id;
  div.innerHTML = [
    `<div class="node-name">${name}</div>`,
    dates        ? `<div class="node-dates">${dates}</div>` : '',
    person.place ? `<div class="node-place">${person.place}</div>` : '',
    person.num != null ? `<span class="node-num">#${person.num}</span>` : '',
  ].join('');
  div.addEventListener('click', () => showDetailPanel(person, div));
  return div;
}

// ── Render ───────────────────────────────────────────────────

function renderTree(tree) {
  if (!tree) return;

  const canvas = document.getElementById('canvas');
  canvas.innerHTML = '';

  const { ancestorTree, families } = tree;

  // ── Ancestor depth & Y_ROOT ───────────────────────────────
  const actualDepth = (function maxDepth(node) {
    if (!node) return 0;
    return 1 + Math.max(maxDepth(node.father), maxDepth(node.mother));
  })(ancestorTree) - 1;

  const Y_ROOT      = 24 + actualDepth * ROW_H;
  const HLINE_Y     = Y_ROOT + Math.round(NODE_H / 2);
  const BASE_DROP_Y = Y_ROOT + ROW_H - 16;

  // ── Spouse layout offsets ─────────────────────────────────
  const SP_GAP  = 32;
  const FAM_GAP = 40;
  const STAGGER = 22;
  const MARGIN  = 20;

  const leftFams  = families.length > 1 ? [families[0]] : [];
  const rightFams = families.length > 1 ? families.slice(1) : families;

  const leftSpouseOffsets  = leftFams.map((_,i)  => -(NODE_W/2 + SP_GAP + NODE_W/2 + i*(NODE_W+SP_GAP)));
  const rightSpouseOffsets = rightFams.map((_,i) =>   NODE_W/2 + SP_GAP + NODE_W/2 + i*(NODE_W+SP_GAP));

  const orderedFams   = [...leftFams, ...rightFams];
  const anchorOffsets = [
    ...leftSpouseOffsets.map(o => o / 2),
    ...rightSpouseOffsets.map(o => o / 2),
  ];

  // ── Compute below-root width ───────────────────────────────
  // Children are grouped by family and rendered sequentially.
  const birthYear = (p) => {
    if (p.birth && p.birth[0]) return p.birth[0];
    const r = SI.find(x => x[0] == p.id);
    return (r && r[6]) || 9999;
  };
  const famBlocks = orderedFams
    .map((fam, fi) => ({ fam, fi, children: fam.children.slice().sort((a,b)=>birthYear(a)-birthYear(b)) }))
    .filter(b => b.children.length > 0);

  famBlocks.sort((A, B) => {
    const aAnchor = orderedFams[A.fi].spouse ? anchorOffsets[A.fi] : 0;
    const bAnchor = orderedFams[B.fi].spouse ? anchorOffsets[B.fi] : 0;
    return aAnchor - bAnchor || birthYear(A.children[0]) - birthYear(B.children[0]);
  });

  const childModeBlockWidths = famBlocks.map(b => b.children.length * (NODE_W + GAP_X) - GAP_X);
  const childModeBelowWidth = childModeBlockWidths.length > 0
    ? childModeBlockWidths.reduce((s,w) => s + w, 0) + (childModeBlockWidths.length - 1) * FAM_GAP
    : 0;
  const descendantLayout = currentMode === 'descendants'
    ? computeDescendantLayout(ancestorTree.person.id)
    : null;
  const belowWidth = descendantLayout ? descendantLayout.width : childModeBelowWidth;
  const belowLeftNeeded = descendantLayout ? descendantLayout.rootOffset : belowWidth / 2;
  const belowRightNeeded = descendantLayout ? descendantLayout.width - descendantLayout.rootOffset : belowWidth / 2;

  // ── Resolve rootCx ────────────────────────────────────────
  const leftSpouseNeeded = leftSpouseOffsets.length
    ? -(leftSpouseOffsets[leftSpouseOffsets.length-1] - NODE_W/2) : 0;
  const ancestorW = slotWidth(ancestorTree);

  const rootCxRaw = Math.max(
    MARGIN + leftSpouseNeeded,
    MARGIN + belowLeftNeeded,
    MARGIN + ancestorW / 2,
  );

  const ancestorPositions = assignAncestorPositions(ancestorTree, rootCxRaw, 0);
  const minAncCx = ancestorPositions.reduce((m, p) => Math.min(m, p.cx), rootCxRaw);
  const shift    = Math.max(0, MARGIN + NODE_W/2 - minAncCx);
  const rootCx   = rootCxRaw + shift;

  const positions = assignAncestorPositions(ancestorTree, rootCx, 0);
  const posMap    = new Map(positions.map(p => [p.person.id, p]));

  // ── Canvas size ───────────────────────────────────────────
  const rightSpouseNeeded = rightSpouseOffsets.length
    ? rightSpouseOffsets[rightSpouseOffsets.length-1] + NODE_W/2 : NODE_W/2;
  const maxAncCx = positions.reduce((m, p) => Math.max(m, p.cx), rootCx);

  const hasAncChildren = orderedFams.some(f => f.children.length > 0);
  const canvasW = Math.ceil(Math.max(
    maxAncCx + NODE_W/2 + MARGIN,
    rootCx + rightSpouseNeeded + MARGIN,
    rootCx + belowRightNeeded + MARGIN,
  ));
  const descendantDepth = currentMode === 'descendants'
    ? computeDescendantDepth(ancestorTree.person.id)
    : (hasAncChildren ? 1 : 0);
  const canvasH = Y_ROOT
    + (descendantDepth + 1) * ROW_H
    + 40;

  canvas.style.cssText = `width:${canvasW}px;height:${canvasH}px;position:relative`;
  const svg = svgEl('svg', { class: 'connectors', style: `width:${canvasW}px;height:${canvasH}px` });
  canvas.appendChild(svg);

  function placeNode(person, cx, y, isRoot = false) {
    const node = createNode(person, cx - NODE_W/2, y, isRoot);
    if (node) canvas.appendChild(node);
  }

  // ── Place ancestor nodes ──────────────────────────────────
  positions.forEach(({ person, cx, depth }) => {
    placeNode(person, cx, Y_ROOT - depth * ROW_H, depth === 0);
  });

  // ── Ancestor connectors ───────────────────────────────────
  positions.forEach(({ person, cx, depth }) => {
    const childY  = Y_ROOT - depth * ROW_H;
    const parentY = Y_ROOT - (depth + 1) * ROW_H;
    const midY    = nodeBot(parentY) + Math.round(GAP_Y * 0.5);
    const [fid, mid] = PA[person.id] || [null, null];
    const fpos = fid ? posMap.get(fid) : null;
    const mpos = mid ? posMap.get(mid) : null;
    if (!fpos && !mpos) return;
    if (fpos && mpos) {
      drawLine(svg, fpos.cx, nodeBot(parentY), fpos.cx, midY, '#7ca8d8');
      drawLine(svg, mpos.cx, nodeBot(parentY), mpos.cx, midY, '#d87898');
      drawBar(svg, fpos.cx, mpos.cx, midY, '#aaa');
      const barMid = (fpos.cx + mpos.cx) / 2;
      if (Math.abs(barMid - cx) > 0.5) drawLine(svg, barMid, midY, cx, midY, '#999');
      drawLine(svg, cx, midY, cx, childY, '#999');
    } else {
      const parentCx = fpos ? fpos.cx : mpos.cx;
      const color    = fpos ? '#7ca8d8' : '#d87898';
      drawLine(svg, parentCx, nodeBot(parentY), parentCx, childY, color);
    }
  });

  // ── Spouses + marriage hlines ─────────────────────────────
  const leftSpouseCx  = leftSpouseOffsets.map(o  => rootCx + o);
  const rightSpouseCx = rightSpouseOffsets.map(o => rootCx + o);
  const anchorCxList  = anchorOffsets.map(o => rootCx + o);

  leftFams.forEach((fam, i) => {
    const scx    = leftSpouseCx[i];
    const fromCx = i === 0 ? rootCx : leftSpouseCx[i-1];
    if (fam.spouse) {
      placeNode(fam.spouse, scx, Y_ROOT);
      drawLine(svg, scx, HLINE_Y, fromCx, HLINE_Y, '#bbb', true);
    }
  });
  rightFams.forEach((fam, i) => {
    const scx    = rightSpouseCx[i];
    const fromCx = i === 0 ? rootCx : rightSpouseCx[i-1];
    if (fam.spouse) {
      placeNode(fam.spouse, scx, Y_ROOT);
      drawLine(svg, fromCx, HLINE_Y, scx, HLINE_Y, '#bbb', true);
    }
  });

  // ── Below root: draw children grouped by family ────────────
  if (currentMode === 'descendants') {
    renderDescendants(svg, ancestorTree, rootCx, Y_ROOT, orderedFams, MARGIN);
  } else {
    renderChildrenMode(svg, rootCx, Y_ROOT, anchorCxList, orderedFams, famBlocks, childModeBelowWidth, MARGIN);
  }

function renderChildrenMode(svg, rootCx, Y_ROOT, anchorCxList, orderedFams, famBlocks, belowWidth, MARGIN) {
  const singleFamilyAnchor = TreeLayout.getAnchorForSingleFamily(famBlocks, anchorCxList);
  const chStart = TreeLayout.computeChildrenStart(rootCx, singleFamilyAnchor, belowWidth, MARGIN);
  const Y_CH = Y_ROOT + ROW_H;
  const drawnAnchors = new Set();
  const placedBlocks = [];

  let cursor = chStart;
  famBlocks.forEach((blk, fi) => {
    const blockWidth = blk.children.length * (NODE_W + GAP_X) - GAP_X;
    const famIndex = blk.fi;
    const anchorCx = orderedFams[famIndex].spouse ? anchorCxList[famIndex] : rootCx;
    const stubStartY = orderedFams[famIndex].spouse ? HLINE_Y : nodeBot(Y_ROOT);
    let familyDropY = BASE_DROP_Y;
    for (const prev of placedBlocks) {
      if (anchorCx >= prev.firstCx && anchorCx <= prev.lastCx) {
        familyDropY = Math.min(familyDropY, prev.familyDropY - STAGGER);
      }
    }
    familyDropY = Math.max(HLINE_Y + 20, familyDropY);
    const key = `${anchorCx},${stubStartY},${familyDropY}`;

    if (!drawnAnchors.has(key)) {
      drawnAnchors.add(key);
      drawLine(svg, anchorCx, stubStartY, anchorCx, familyDropY, '#7bc8a8');
    }

    const blockLeft = cursor;
    const firstCx = nodeCx(blockLeft);
    const lastCx = nodeCx(blockLeft + blockWidth - NODE_W);

    if (blk.children.length > 1) drawBar(svg, firstCx, lastCx, familyDropY, '#7bc8a8');

    if (anchorCx < firstCx) drawLine(svg, anchorCx, familyDropY, firstCx, familyDropY, '#7bc8a8');
    else if (anchorCx > lastCx) drawLine(svg, lastCx, familyDropY, anchorCx, familyDropY, '#7bc8a8');

    blk.children.forEach((child, ci) => {
      let childCx;
      if (blk.children.length === 1) {
        childCx = anchorCx;
      } else {
        childCx = nodeCx(blockLeft + ci * (NODE_W + GAP_X));
      }
      placeNode(child, childCx, Y_CH);
      drawLine(svg, childCx, familyDropY, childCx, Y_CH, '#7bc8a8');
    });

    placedBlocks.push({ firstCx, lastCx, familyDropY });
    cursor += blockWidth + FAM_GAP;
  });
}

function renderDescendants(svg, ancestorTree, rootCx, Y_ROOT, orderedFams, MARGIN) {
  const rootFamilies = orderedFams.filter(Boolean);
  let queue = renderDescendantParent(svg, ancestorTree.person, rootCx, Y_ROOT, rootFamilies, false, MARGIN);

  while (queue.length) {
    const nextQueue = [];
    for (const { person, cx, y } of queue) {
      const families = buildFamilyGroups(person.id).filter(Boolean);
      if (!families.length) continue;
      nextQueue.push(...renderDescendantParent(svg, person, cx, y, families, true, MARGIN));
    }
    queue = nextQueue;
  }
}

function renderDescendantParent(svg, parent, parentCx, parentY, families, renderSpouses, MARGIN) {
  families = (families || []).filter(Boolean);
  if (!families.length) return [];

  const Y_CH = parentY + ROW_H;
  const baseDropY = parentY + ROW_H - 16;
  const orderedFams = families.length > 1 ? [families[0], ...families.slice(1)] : families;
  const leftFams = families.length > 1 ? [families[0]] : [];
  const rightFams = families.length > 1 ? families.slice(1) : families;
  const leftSpouseOffsets = leftFams.map((_, i) => -(NODE_W / 2 + SP_GAP + NODE_W / 2 + i * (NODE_W + SP_GAP)));
  const rightSpouseOffsets = rightFams.map((_, i) => NODE_W / 2 + SP_GAP + NODE_W / 2 + i * (NODE_W + SP_GAP));
  const anchorOffsets = [...leftSpouseOffsets.map(o => o / 2), ...rightSpouseOffsets.map(o => o / 2)];
  const anchorCxList = anchorOffsets.map(o => parentCx + o);

  if (renderSpouses) {
    leftFams.forEach((fam, i) => {
      const scx = parentCx + leftSpouseOffsets[i];
      const fromCx = i === 0 ? parentCx : parentCx + leftSpouseOffsets[i - 1];
      if (fam.spouse) {
        placeNode(fam.spouse, scx, parentY);
        const hlineY = parentY + Math.round(NODE_H / 2);
        drawLine(svg, scx, hlineY, fromCx, hlineY, '#bbb', true);
      }
    });
    rightFams.forEach((fam, i) => {
      const scx = parentCx + rightSpouseOffsets[i];
      const fromCx = i === 0 ? parentCx : parentCx + rightSpouseOffsets[i - 1];
      if (fam.spouse) {
        placeNode(fam.spouse, scx, parentY);
        const hlineY = parentY + Math.round(NODE_H / 2);
        drawLine(svg, fromCx, hlineY, scx, hlineY, '#bbb', true);
      }
    });
  }

  const famBlocks = orderedFams.map((fam, fi) => {
    const children = Array.isArray(fam.children) ? fam.children : [];
    const childLayouts = children.map(child => computeDescendantLayout(child.id));
    const childrenWidth = childLayouts.length
      ? childLayouts.reduce((sum, l) => sum + l.width, 0) + (childLayouts.length - 1) * GAP_X
      : NODE_W;
    const spouseSpan = fam.spouse
      ? NODE_W + SP_GAP + NODE_W
      : NODE_W;
    const blockWidth = Math.max(childrenWidth, spouseSpan, NODE_W);
    return { fam, fi, children, childLayouts, childrenWidth, blockWidth };
  });
  const blockWidths = famBlocks.map(b => b.blockWidth);
  const belowWidth = blockWidths.length > 0
    ? blockWidths.reduce((sum, width) => sum + width, 0) + (blockWidths.length - 1) * FAM_GAP
    : 0;
  const singleFamilyAnchor = TreeLayout.getAnchorForSingleFamily(famBlocks, anchorCxList);
  const chStart = TreeLayout.computeChildrenStart(parentCx, singleFamilyAnchor, belowWidth, MARGIN);
  const drawnAnchors = new Set();
  const placedBlocks = [];
  const childPositions = [];

  let cursor = chStart;
  famBlocks.forEach((blk, fi) => {
    const blockWidth = blk.blockWidth;
    const famIndex = blk.fi;
    const anchorCx = blk.fam.spouse ? parentCx + anchorOffsets[famIndex] : parentCx;
    const stubStartY = blk.fam.spouse ? parentY + Math.round(NODE_H / 2) : nodeBot(parentY);
    let familyDropY = baseDropY;
    for (const prev of placedBlocks) {
      if (anchorCx >= prev.firstCx && anchorCx <= prev.lastCx) {
        familyDropY = Math.min(familyDropY, prev.familyDropY - STAGGER);
      }
    }
    familyDropY = Math.max(stubStartY + 20, familyDropY);
    const key = `${anchorCx},${stubStartY},${familyDropY}`;

    if (!drawnAnchors.has(key) && blk.children.length) {
      drawnAnchors.add(key);
      drawLine(svg, anchorCx, stubStartY, anchorCx, familyDropY, '#7bc8a8');
    }

    const blockLeft = cursor;
    const childBlockLeft = blockLeft + Math.max(0, (blockWidth - blk.childrenWidth) / 2);
    
    const childCenters = [];
    let childCursor = childBlockLeft;
    blk.children.forEach((child, ci) => {
      const childCx = childCursor + blk.childLayouts[ci].rootOffset;
      childCenters.push(childCx);
      childCursor += blk.childLayouts[ci].width + GAP_X;
    });

    const firstCx = blk.children.length ? childCenters[0] : blockLeft + blk.childrenWidth / 2;
    const lastCx = blk.children.length ? childCenters[childCenters.length - 1] : blockLeft + blk.childrenWidth / 2;

    if (blk.children.length > 1) drawBar(svg, firstCx, lastCx, familyDropY, '#7bc8a8');
    if (blk.children.length && anchorCx < firstCx) drawLine(svg, anchorCx, familyDropY, firstCx, familyDropY, '#7bc8a8');
    else if (blk.children.length && anchorCx > lastCx) drawLine(svg, lastCx, familyDropY, anchorCx, familyDropY, '#7bc8a8');

    childCursor = childBlockLeft;
    blk.children.forEach((child, ci) => {
      const childLayout = blk.childLayouts[ci];
      const childCx = childCursor + childLayout.rootOffset;
      placeNode(child, childCx, Y_CH);
      drawLine(svg, childCx, familyDropY, childCx, Y_CH, '#7bc8a8');
      childPositions.push({ person: child, cx: childCx, y: Y_CH });
      childCursor += childLayout.width + GAP_X;
    });

    placedBlocks.push({ firstCx: blockLeft, lastCx: blockLeft + blockWidth, familyDropY });
    cursor += blockWidth + FAM_GAP;
  });

  return childPositions;
}

  // ── Update state ──────────────────────────────────────────
  currentRootId = ancestorTree.person.id;
  document.getElementById('crumb').textContent =
    formatName(ancestorTree.person.given, ancestorTree.person.patronymic,
               ancestorTree.person.surname, ancestorTree.person.maiden);

  const newHash = `#${currentRootId}`;
  if (location.hash !== newHash) history.replaceState(null, '', newHash);

  // Centre root in viewport
  {
    const toolbar = document.getElementById('toolbar');
    const vw = window.innerWidth;
    const vh = window.innerHeight - (toolbar ? toolbar.offsetHeight : 48);
    const targetX = Math.round(vw / 2);
    const targetY = Math.round(vh / 3);
    const padLeft = Math.max(0, targetX - rootCx);
    const padTop  = Math.max(0, targetY - Y_ROOT);
    canvas.style.cssText += `;margin-left:${padLeft}px;margin-top:${padTop}px`;
    const wrap = document.getElementById('canvas-wrap');
    wrap.scrollLeft = Math.max(0, rootCx + padLeft - targetX);
    wrap.scrollTop  = Math.max(0, Y_ROOT + padTop  - targetY);
  }
}

// ── Detail panel ─────────────────────────────────────────────

function showDetailPanel(person, node) {
  document.querySelectorAll('.node.is-selected').forEach(n => n.classList.remove('is-selected'));
  if (node) node.classList.add('is-selected');

  const name = formatName(person.given, person.patronymic, person.surname, person.maiden)
             || `Асоба #${person.id}`;
  document.getElementById('detail-name').textContent = name;

  const infoParts = [];
  if (person.birth) infoParts.push(`Нар.: ${formatDate(person.birth)}`);
  if (person.death) infoParts.push(`Пам.: ${formatDate(person.death)}`);
  if (person.place) infoParts.push(person.place);
  if (person.num != null) infoParts.push(`#${person.num}`);
  document.getElementById('detail-info').textContent = infoParts.join('  ·  ');

  const nav = document.getElementById('detail-nav');
  nav.innerHTML = '';
  if (person.id !== currentRootId) {
    const btn = document.createElement('button');
    btn.className = 'nav-btn';
    btn.textContent = 'Паказаць дрэва →';
    btn.addEventListener('click', () => navigate(person.id));
    nav.appendChild(btn);
  }

  document.getElementById('detail-panel').style.display = 'flex';
}

// ── Navigation ───────────────────────────────────────────────

function navigate(id) {
  document.getElementById('detail-panel').style.display = 'none';
  renderTree(buildTree(id));
}

function setMode(mode) {
  currentMode = mode;
  document.querySelectorAll('.mode-btn').forEach(b => {
    b.classList.toggle('mode-btn-active', b.dataset.mode === mode);
  });
  if (currentRootId) renderTree(buildTree(currentRootId));
}

function initUI() {
  document.getElementById('btn-home').addEventListener('click', () => navigate(CONFIG.homeId));

  // Mode buttons
  document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', () => setMode(btn.dataset.mode));
  });

  document.getElementById('detail-close').addEventListener('click', () => {
    document.getElementById('detail-panel').style.display = 'none';
    document.querySelectorAll('.node.is-selected').forEach(n => n.classList.remove('is-selected'));
  });

  window.addEventListener('hashchange', () => {
    const id = parseInt(location.hash.slice(1));
    if (id && id !== currentRootId) navigate(id);
  });
}

// ── Search ───────────────────────────────────────────────────

function initSearch() {
  const input   = document.getElementById('search-input');
  const results = document.getElementById('search-results');
  let debounce  = null;

  input.addEventListener('input', () => {
    clearTimeout(debounce);
    const raw = input.value.trim().toLowerCase();
    if (raw.length < 2) { results.style.display = 'none'; return; }

    debounce = setTimeout(() => {
      // Split query into words; every word must match somewhere in the name fields
      const words = raw.split(/\s+/).filter(Boolean);

      const matches = [];
      for (const r of SI) {
        const [id, sex, given, patronymic, surname, maiden, birthYear] = r;
        const fields = [given, patronymic, surname, maiden]
          .filter(Boolean)
          .map(s => s.toLowerCase());

        // Every query word must prefix-match at least one field token
        const allMatch = words.every(w =>
          fields.some(f => f.startsWith(w) || f.includes(w))
        );
        if (!allMatch) continue;

        // Score: prefer matches where more fields start with a query word
        const score = words.reduce((s, w) =>
          s + (fields.some(f => f.startsWith(w)) ? 1 : 0), 0
        );
        matches.push({ r, score });
        if (matches.length >= 50) break; // collect candidates then sort
      }

      // Sort: higher score first, then by birth year
      matches.sort((a, b) =>
        b.score - a.score || ((a.r[6] || 9999) - (b.r[6] || 9999))
      );

      results.innerHTML = '';
      if (!matches.length) { results.style.display = 'none'; return; }

      matches.slice(0, 10).forEach(({ r }) => {
        const [id, sex, given, patronymic, surname, maiden, birthYear] = r;
        const name = formatName(given, patronymic, surname, maiden) || `Асоба #${id}`;
        const div  = document.createElement('div');
        div.className = 'search-result';
        div.innerHTML = `
          <div class="search-result-name">${name}</div>
          <div class="search-result-sub">${surname || ''}${birthYear ? ' н.' + birthYear : ''} ${sex === 1 ? 'муж.' : 'жан.'}</div>
        `.trim();
        div.addEventListener('click', () => {
          results.style.display = 'none';
          input.value = '';
          navigate(id);
        });
        results.appendChild(div);
      });

      results.style.display = 'block';
    }, 250);
  });

  document.addEventListener('click', e => {
    if (!input.contains(e.target) && !results.contains(e.target)) {
      results.style.display = 'none';
    }
  });
}

