/**
 * tree.js — Veliatychi family tree visualiser
 *
 * Data is loaded from JSON files in data/ (generated by export.py).
 * Navigation is driven by URL hash: #<person_id>
 */

'use strict';

// ── Configuration ────────────────────────────────────────────
const CONFIG = {
  homeId:   11083,      // default person on first load — change to suit
  dataDir:  'data/',
  dataFiles: ['si', 'parents', 'children', 'marriages', 'places', 'nums', 'births', 'deaths'],
};

// ── Layout constants ─────────────────────────────────────────
const NODE_W   = 152;  // node width (px)
const NODE_H   = 88;   // node min-height (px) — used for spacing only
const GAP_X    = 20;   // horizontal gap between sibling nodes
const GAP_Y    = 80;   // vertical gap between generation rows
const ROW_H    = NODE_H + GAP_Y;
const SP_GAP   = 32;   // gap between root node edge and spouse node edge
const FAM_GAP  = 40;   // gap between children groups of different spouses
const STAGGER  = 22;   // vertical stagger between family drop bars (px)
const LABEL_W  = 90;   // left margin reserved for generation labels

// Derived row Y positions (relative to canvas top)
const Y_GGP  = 24;                    // great-grandparents
const Y_GP   = Y_GGP + ROW_H;        // grandparents
const Y_PAR  = Y_GP  + ROW_H;        // parents + root + spouses
const Y_CH   = Y_PAR + ROW_H;        // children
const Y_GCH  = Y_CH  + ROW_H;        // grandchildren (label only)

const HLINE_Y    = Y_PAR + Math.round(NODE_H / 2);  // marriage line Y
const BASE_DROP_Y = Y_PAR + NODE_H + 36;             // top of first child drop bar

// ── Global data store ─────────────────────────────────────────
// Populated by loadData(). Short names match JSON file names.
let SI; // search index: [[id, sex, given, patronymic, surname, maiden, birth_year], ...]
let PA; // parents:      {child_id: [father_id, mother_id]}
let CH; // children:     {parent_id: [child_id, ...]}
let MA; // marriages:    {person_id: [[spouse_id, [y,m,d], [child_ids]], ...]}
let PL; // places:       {person_id: "place name"}
let NU; // nums:         {person_id: integer}
let BI; // births:       {person_id: [y, m, d]}
let DE; // deaths:       {person_id: [y, m, d]}

let currentRootId = null;
let currentMode   = 'ancestors'; // 'ancestors' | 'descendants'

// ── Bootstrap ────────────────────────────────────────────────
(async function init() {
  await loadData();
  const startId = parseInt(location.hash.slice(1)) || CONFIG.homeId;
  renderTree(buildTree(startId));
  initSearch();
  initUI();
})();

// ── Data loading ─────────────────────────────────────────────
async function loadData() {
  const fill = document.getElementById('loading-fill');
  const msg  = document.getElementById('loading-msg');

  try {
    const results = {};
    for (let i = 0; i < CONFIG.dataFiles.length; i++) {
      const name = CONFIG.dataFiles[i];
      msg.textContent = `Загрузка ${name}…`;
      const resp = await fetch(CONFIG.dataDir + name + '.json');
      if (!resp.ok) throw new Error(`Failed to fetch ${name}.json (HTTP ${resp.status})`);
      results[name] = await resp.json();
      fill.style.width = Math.round((i + 1) / CONFIG.dataFiles.length * 100) + '%';
    }
    ({ si: SI, parents: PA, children: CH, marriages: MA,
       places: PL, nums: NU, births: BI, deaths: DE } = results);
    document.getElementById('loading').style.display = 'none';

  } catch (err) {
    document.getElementById('loading').style.display = 'none';
    document.getElementById('err-msg').textContent =
      err.message + '\n\nПераканайцеся, што файлы JSON знаходзяцца ў папцы data/. Запусціце export.py для іх стварэння.';
    document.getElementById('err').style.display = 'flex';
    throw err; // stop execution
  }
}

// ── Data helpers ─────────────────────────────────────────────

/** Format a [year, month, day] date tuple as dd.mm.yyyy */
function formatDate(d) {
  if (!d) return '?';
  const [y, m, dd] = d;
  if (!y)  return '?';
  if (!m)  return String(y);
  const pad = n => n ? String(n).padStart(2, '0') : '??';
  if (!dd) return `??.${pad(m)}.${y}`;
  return `${pad(dd)}.${pad(m)}.${y}`;
}

/** Build a display name: Surname (Maiden) Given Patronymic */
function formatName(given, patronymic, surname, maiden) {
  const surnamePart = surname
    ? (maiden && maiden !== surname ? `${surname} (${maiden})` : surname)
    : (maiden || null);
  return [surnamePart, given, patronymic].filter(Boolean).join(' ');
}

/** Build a person object from the data store */
/** Build a person object from the data store */
function buildPerson(id) {
  if (!id) return null;
  const r = SI.find(x => x[0] == id);
  if (!r && !BI[id] && !DE[id]) return null;
  return {
    id,
    sex:        r ? r[1] : 0,
    given:      r ? r[2] : null,
    patronymic: r ? r[3] : null,
    surname:    r ? r[4] : null,
    maiden:     r ? r[5] : null,
    birth:      BI[id] || null,
    death:      DE[id] || null,
    place:      PL[id] || null,
    num:        NU[id] ?? null,
  };
}

/**
 * Recursively build an ancestor subtree node.
 * Each node: { person, father, mother } (father/mother are ancestor nodes or null).
 */
const MAX_ANCESTOR_GENERATIONS = 4;

function buildAncestorNode(id, depth) {
  if (!id || depth >= MAX_ANCESTOR_GENERATIONS) return null;
  const person = buildPerson(id);
  if (!person) return null;
  const [fatherId, motherId] = PA[id] || [null, null];
  return {
    person,
    father: buildAncestorNode(fatherId, depth + 1),
    mother: buildAncestorNode(motherId, depth + 1),
  };
}

/** Compute the minimum horizontal slot width needed for an ancestor subtree. */
function slotWidth(node) {
  if (!node) return 0;
  const fw = slotWidth(node.father);
  const mw = slotWidth(node.mother);
  if (!fw && !mw) return NODE_W;
  if (!fw) return Math.max(NODE_W, mw);
  if (!mw) return Math.max(NODE_W, fw);
  return Math.max(NODE_W, fw + GAP_X + mw);
}

/**
 * Assign cx (horizontal centre) to every ancestor node, top-down.
 * Returns flat array of { person, cx, depth } for all ancestors.
 * depth=0 is the root, depth=1 is parents, etc.
 */
function assignAncestorPositions(node, cx, depth, results = []) {
  if (!node) return results;
  results.push({ person: node.person, cx, depth });
  const fw = slotWidth(node.father);
  const mw = slotWidth(node.mother);
  if (node.father && node.mother) {
    // Two parents: place symmetrically left (father) and right (mother)
    const totalW = fw + GAP_X + mw;
    assignAncestorPositions(node.father, cx - totalW/2 + fw/2,  depth + 1, results);
    assignAncestorPositions(node.mother, cx + totalW/2 - mw/2, depth + 1, results);
  } else if (node.father) {
    // Single parent: directly above
    assignAncestorPositions(node.father, cx, depth + 1, results);
  } else if (node.mother) {
    assignAncestorPositions(node.mother, cx, depth + 1, results);
  }
  return results;
}

/** Build the full tree data structure centred on rootId. */
function buildTree(rootId) {
  const root = buildPerson(rootId);
  if (!root) return null;

  const [fatherId, motherId] = PA[rootId] || [null, null];
  const ancestorTree = {
    person: root,
    father: buildAncestorNode(fatherId, 0),
    mother: buildAncestorNode(motherId, 0),
  };

  const families = (MA[rootId] || []).map(([spouseId, marriageDate, childIds]) => {
    // childIds from MA is the per-couple list; fall back to all children if empty
    const children = (childIds && childIds.length)
      ? childIds.map(buildPerson).filter(Boolean)
      : [];
    return {
      spouse:   buildPerson(spouseId),
      date:     marriageDate,
      children,
    };
  });

  // Fallback: no marriage records at all — use CH map
  if (!families.length) {
    const ch = (CH[rootId] || []).map(buildPerson).filter(Boolean);
    if (ch.length) families.push({ spouse: null, date: null, children: ch });
  }

  // Any children not accounted for in MA get their own anonymous family
  const allKnownChildren = new Set(families.flatMap(f => f.children.map(c => c.id)));
  const chChildren = (CH[rootId] || []).map(buildPerson).filter(Boolean);
  const unknownChildren = chChildren.filter(c => !allKnownChildren.has(c.id));
  if (unknownChildren.length) {
    families.push({ spouse: null, date: null, children: unknownChildren });
  }

  // Remove families that have neither spouse nor children (nothing to show)
  const validFamilies = families.filter(f => f.spouse || f.children.length);

  validFamilies.forEach(fam => {
    fam.children.sort((a, b) =>
      ((a.birth && a.birth[0]) || 9999) - ((b.birth && b.birth[0]) || 9999)
    );
  });

  return { ancestorTree, families: validFamilies, descendantTree: null };
}

/** Attach descendant tree to an already-built tree object */
function attachDescendants(tree) {
  if (!tree.descendantTree) {
    tree.descendantTree = buildDescendantNode(tree.ancestorTree.person.id, 0);
  }
}

// ── Layout helpers ───────────────────────────────────────────

/** X centre of a node placed at left edge x */
const nodeCx = x => x + NODE_W / 2;

/** Y bottom of a node placed at top edge y */
const nodeBot = y => y + NODE_H;

// ── SVG helpers ──────────────────────────────────────────────

function svgEl(tag, attrs) {
  const el = document.createElementNS('http://www.w3.org/2000/svg', tag);
  for (const [k, v] of Object.entries(attrs)) el.setAttribute(k, v);
  return el;
}

function drawLine(svg, x1, y1, x2, y2, stroke, dashed = false) {
  const attrs = { x1, y1, x2, y2, stroke, 'stroke-width': '1.5' };
  if (dashed) attrs['stroke-dasharray'] = '5,4';
  svg.appendChild(svgEl('line', attrs));
}

function drawBar(svg, cx1, cx2, y, stroke) {
  drawLine(svg, Math.min(cx1, cx2), y, Math.max(cx1, cx2), y, stroke);
}

// ── Node DOM helpers ─────────────────────────────────────────

function createNode(person, x, y, isRoot = false) {
  if (!person) return null;
  const name = formatName(person.given, person.patronymic, person.surname, person.maiden)
             || `Асоба #${person.id}`;
  const dates = (person.birth || person.death)
    ? `${formatDate(person.birth)} — ${formatDate(person.death)}` : '';
  const div = document.createElement('div');
  div.className = ['node',
    person.sex === 1 ? 'sex-m' : person.sex === 2 ? 'sex-f' : '',
    isRoot ? 'is-root' : ''].filter(Boolean).join(' ');
  div.style.cssText = `left:${x}px;top:${y}px`;
  div.dataset.id = person.id;
  div.innerHTML = [
    `<div class="node-name">${name}</div>`,
    dates        ? `<div class="node-dates">${dates}</div>` : '',
    person.place ? `<div class="node-place">${person.place}</div>` : '',
    person.num != null ? `<span class="node-num">#${person.num}</span>` : '',
  ].join('');
  div.addEventListener('click', () => showDetailPanel(person, div));
  return div;
}

// ── Render ───────────────────────────────────────────────────

function renderTree(tree) {
  if (!tree) return;

  const canvas = document.getElementById('canvas');
  canvas.innerHTML = '';

  const { ancestorTree, families } = tree;
  const descMode = currentMode === 'descendants';

  // ── Ancestor depth & Y_ROOT ───────────────────────────────
  const actualDepth = (function maxDepth(node) {
    if (!node) return 0;
    return 1 + Math.max(maxDepth(node.father), maxDepth(node.mother));
  })(ancestorTree) - 1;

  const Y_ROOT      = 24 + actualDepth * ROW_H;
  const HLINE_Y     = Y_ROOT + Math.round(NODE_H / 2);
  // BASE_DROP_Y: always within the gap below root, regardless of card height
  const BASE_DROP_Y = Y_ROOT + ROW_H - 16;

  // ── Spouse layout offsets ─────────────────────────────────
  const SP_GAP  = 32;
  const FAM_GAP = 40;
  const STAGGER = 22;
  const MARGIN  = 20;

  const leftFams  = families.length > 1 ? [families[0]] : [];
  const rightFams = families.length > 1 ? families.slice(1) : families;

  const leftSpouseOffsets  = leftFams.map((_,i)  => -(NODE_W/2 + SP_GAP + NODE_W/2 + i*(NODE_W+SP_GAP)));
  const rightSpouseOffsets = rightFams.map((_,i) =>   NODE_W/2 + SP_GAP + NODE_W/2 + i*(NODE_W+SP_GAP));

  const orderedFams   = [...leftFams, ...rightFams];
  const anchorOffsets = [
    ...leftSpouseOffsets.map(o => o / 2),
    ...rightSpouseOffsets.map(o => o / 2),
  ];

  // ── Children width (ancestors mode) vs descendant width ───
  // In descendants mode, child spacing is driven by subtree widths.
  // We still need the descendant tree for width calculation.
  if (descMode) attachDescendants(tree);
  const descNode = descMode ? tree.descendantTree : null;

  // Width below root:
  //   ancestors mode  → fixed-width children groups
  //   descendants mode → recursive subtree width
  const groupWidths = orderedFams.map(fam =>
    fam.children.length > 0 ? fam.children.length * (NODE_W + GAP_X) - GAP_X : 0
  );
  // Ancestors mode renders all children as one flat sorted row
  const allChildrenCount = orderedFams.reduce((s, f) => s + f.children.length, 0);
  const totalChildrenWidthAnc = allChildrenCount > 0
    ? allChildrenCount * (NODE_W + GAP_X) - GAP_X
    : 0;

  const belowWidth = descMode && descNode
    ? descSubtreeWidth(descNode)
    : totalChildrenWidthAnc;

  // ── Resolve rootCx ────────────────────────────────────────
  const leftSpouseNeeded = leftSpouseOffsets.length
    ? -(leftSpouseOffsets[leftSpouseOffsets.length-1] - NODE_W/2) : 0;
  const ancestorW = slotWidth(ancestorTree);

  const rootCxRaw = Math.max(
    MARGIN + leftSpouseNeeded,
    MARGIN + belowWidth / 2,
    MARGIN + ancestorW / 2,
  );

  const ancestorPositions = assignAncestorPositions(ancestorTree, rootCxRaw, 0);
  const minAncCx = ancestorPositions.reduce((m, p) => Math.min(m, p.cx), rootCxRaw);
  const shift    = Math.max(0, MARGIN + NODE_W/2 - minAncCx);
  const rootCx   = rootCxRaw + shift;

  const positions = assignAncestorPositions(ancestorTree, rootCx, 0);
  const posMap    = new Map(positions.map(p => [p.person.id, p]));

  // ── Canvas size ───────────────────────────────────────────
  const rightSpouseNeeded = rightSpouseOffsets.length
    ? rightSpouseOffsets[rightSpouseOffsets.length-1] + NODE_W/2 : NODE_W/2;
  const maxAncCx = positions.reduce((m, p) => Math.max(m, p.cx), rootCx);

  // Descendant tree max extent — compute correct slotLeft first
  let descSlotLeft = rootCx; // fallback
  let descMaxRight = rootCx + NODE_W/2, descMaxDepth = 0;
  if (descMode && descNode) {
    const dnSlotW  = descSubtreeWidth(descNode);
    const dnFamSW  = descNode.families.length ? descNode.families.map(descFamilySlotWidth) : [NODE_W];
    let dnTotalW = NODE_W;
    if (descNode.families.length) {
      dnTotalW = dnFamSW.reduce((s,w)=>s+w,0);
      descNode.families.forEach((fam, fi) => {
        if (fi < descNode.families.length - 1)
          dnTotalW += descFamilyGap(fam, descNode.families[fi + 1]);
      });
    }
    const dnFam0   = descNode.families.length ? descNode.families[0] : null;
    const dnFam0SW = dnFamSW[0] || NODE_W;
    const dnFam0Centre = (dnSlotW - dnTotalW) / 2 + dnFam0SW / 2; // relative to slotLeft
    const dnPersonOffset = dnFam0 && dnFam0.spouse
      ? dnFam0Centre - (NODE_W + DESC_SP_GAP + NODE_W) / 2 + NODE_W / 2
      : dnFam0Centre;
    descSlotLeft = rootCx - dnPersonOffset;

    const dpos = assignDescendantPositions(descNode, descSlotLeft, 0);
    dpos.forEach(({ cx, depth }) => {
      descMaxRight = Math.max(descMaxRight, cx + NODE_W/2);
      descMaxDepth = Math.max(descMaxDepth, depth);
    });
    // also account for spouse nodes extending right
    dpos.forEach(({ node }) => {
      node.families.forEach(fam => {
        if (fam._spouseCx) descMaxRight = Math.max(descMaxRight, fam._spouseCx + NODE_W/2);
      });
    });
  }

  const hasAncChildren = orderedFams.some(f => f.children.length > 0);
  const canvasW = Math.ceil(Math.max(
    maxAncCx + NODE_W/2 + MARGIN,
    descMaxRight + MARGIN,
    rootCx + rightSpouseNeeded + MARGIN,
    rootCx + belowWidth/2 + MARGIN,
  ));
  const canvasH = Y_ROOT
    + (descMode ? (descMaxDepth + 1) * ROW_H : (hasAncChildren ? 2 : 1) * ROW_H)
    + 40;

  canvas.style.cssText = `width:${canvasW}px;height:${canvasH}px;position:relative`;
  const svg = svgEl('svg', { class: 'connectors', style: `width:${canvasW}px;height:${canvasH}px` });
  canvas.appendChild(svg);

  function placeNode(person, cx, y, isRoot = false) {
    const node = createNode(person, cx - NODE_W/2, y, isRoot);
    if (node) canvas.appendChild(node);
  }

  // ── Place ancestor nodes ──────────────────────────────────
  positions.forEach(({ person, cx, depth }) => {
    placeNode(person, cx, Y_ROOT - depth * ROW_H, depth === 0);
  });

  // ── Ancestor connectors ───────────────────────────────────
  positions.forEach(({ person, cx, depth }) => {
    const childY  = Y_ROOT - depth * ROW_H;
    const parentY = Y_ROOT - (depth + 1) * ROW_H;
    const midY    = nodeBot(parentY) + Math.round(GAP_Y * 0.5);
    const [fid, mid] = PA[person.id] || [null, null];
    const fpos = fid ? posMap.get(fid) : null;
    const mpos = mid ? posMap.get(mid) : null;
    if (!fpos && !mpos) return;
    if (fpos && mpos) {
      drawLine(svg, fpos.cx, nodeBot(parentY), fpos.cx, midY, '#7ca8d8');
      drawLine(svg, mpos.cx, nodeBot(parentY), mpos.cx, midY, '#d87898');
      drawBar(svg, fpos.cx, mpos.cx, midY, '#aaa');
      const barMid = (fpos.cx + mpos.cx) / 2;
      if (Math.abs(barMid - cx) > 0.5) drawLine(svg, barMid, midY, cx, midY, '#999');
      drawLine(svg, cx, midY, cx, childY, '#999');
    } else {
      const parentCx = fpos ? fpos.cx : mpos.cx;
      const color    = fpos ? '#7ca8d8' : '#d87898';
      drawLine(svg, parentCx, nodeBot(parentY), parentCx, childY, color);
    }
  });

  // ── Spouses + marriage hlines ─────────────────────────────
  // In descendants mode, renderDescendants handles all families below root.
  // We still draw the root's spouses here so they appear at the root row,
  // but only if the family actually has a spouse (no dangling hlines).
  const leftSpouseCx  = leftSpouseOffsets.map(o  => rootCx + o);
  const rightSpouseCx = rightSpouseOffsets.map(o => rootCx + o);
  const anchorCxList  = anchorOffsets.map(o => rootCx + o);

  if (!descMode) {
    leftFams.forEach((fam, i) => {
      const scx    = leftSpouseCx[i];
      const fromCx = i === 0 ? rootCx : leftSpouseCx[i-1];
      if (fam.spouse) {
        placeNode(fam.spouse, scx, Y_ROOT);
        drawLine(svg, scx, HLINE_Y, fromCx, HLINE_Y, '#bbb', true);
      }
    });
    rightFams.forEach((fam, i) => {
      const scx    = rightSpouseCx[i];
      const fromCx = i === 0 ? rootCx : rightSpouseCx[i-1];
      if (fam.spouse) {
        placeNode(fam.spouse, scx, Y_ROOT);
        drawLine(svg, fromCx, HLINE_Y, scx, HLINE_Y, '#bbb', true);
      }
    });
  }

  // ── Below root: ancestors mode = flat children ────────────
  if (!descMode) {
    // Birth year helper — fallback to SI index if no birth event recorded
    const birthYear = (p) => {
      if (p.birth && p.birth[0]) return p.birth[0];
      const r = SI.find(x => x[0] == p.id);
      return (r && r[6]) || 9999;
    };

    // Build child→family map for correct anchor (hline midpoint vs card bottom)
    const childFamMap = new Map();
    orderedFams.forEach((fam, fi) => {
      fam.children.forEach(c => childFamMap.set(c.id, { fam, fi }));
    });

    // All children sorted globally by birth year ascending
    const allChildren = orderedFams
      .flatMap(fam => fam.children)
      .sort((a, b) => birthYear(a) - birthYear(b));

    if (allChildren.length) {
      const chTotalW  = allChildren.length * (NODE_W + GAP_X) - GAP_X;
      const chStart   = Math.max(MARGIN, rootCx - chTotalW / 2);
      const dropY     = BASE_DROP_Y;
      const Y_CH      = Y_ROOT + ROW_H;
      const firstChCx = nodeCx(chStart);
      const lastChCx  = nodeCx(chStart + (allChildren.length - 1) * (NODE_W + GAP_X));

      // Draw per-family stubs from correct anchor
      // (hline midpoint when spouse known, card bottom when not)
      const drawnAnchors = new Set();
      orderedFams.forEach((fam, fi) => {
        if (!fam.children.length) return;
        const anchorCx  = fam.spouse ? anchorCxList[fi] : rootCx;
        const stubStartY = fam.spouse ? HLINE_Y : nodeBot(Y_ROOT);
        const key = `${anchorCx},${stubStartY}`;
        if (!drawnAnchors.has(key)) {
          drawnAnchors.add(key);
          drawLine(svg, anchorCx, stubStartY, anchorCx, dropY, '#7bc8a8');
        }
      });

      // Horizontal bar spanning all children
      if (allChildren.length > 1) drawBar(svg, firstChCx, lastChCx, dropY, '#7bc8a8');

      // Extend bar to any stub that lands outside the children span
      drawnAnchors.forEach(key => {
        const anchorCx = parseInt(key.split(',')[0]);
        if (anchorCx < firstChCx) drawLine(svg, anchorCx, dropY, firstChCx, dropY, '#7bc8a8');
        else if (anchorCx > lastChCx) drawLine(svg, lastChCx, dropY, anchorCx, dropY, '#7bc8a8');
      });

      allChildren.forEach((child, ci) => {
        const x = chStart + ci * (NODE_W + GAP_X);
        placeNode(child, nodeCx(x), Y_CH);
        drawLine(svg, nodeCx(x), dropY, nodeCx(x), Y_CH, '#7bc8a8');
      });
    }

  // ── Below root: descendants mode = recursive subtree ──────
  } else if (descNode) {
    renderDescendants(svg, canvas, descNode, descSlotLeft, Y_ROOT);
  }

  // ── Update state ──────────────────────────────────────────
  currentRootId = ancestorTree.person.id;
  document.getElementById('crumb').textContent =
    formatName(ancestorTree.person.given, ancestorTree.person.patronymic,
               ancestorTree.person.surname, ancestorTree.person.maiden);

  const newHash = `#${currentRootId}`;
  if (location.hash !== newHash) history.replaceState(null, '', newHash);

  // Centre root in viewport
  {
    const toolbar = document.getElementById('toolbar');
    const vw = window.innerWidth;
    const vh = window.innerHeight - (toolbar ? toolbar.offsetHeight : 48);
    const targetX = Math.round(vw / 2);
    const targetY = Math.round(vh / 3);
    const padLeft = Math.max(0, targetX - rootCx);
    const padTop  = Math.max(0, targetY - Y_ROOT);
    canvas.style.cssText += `;margin-left:${padLeft}px;margin-top:${padTop}px`;
    const wrap = document.getElementById('canvas-wrap');
    wrap.scrollLeft = Math.max(0, rootCx + padLeft - targetX);
    wrap.scrollTop  = Math.max(0, Y_ROOT + padTop  - targetY);
  }
}

// ── Detail panel ─────────────────────────────────────────────

function showDetailPanel(person, node) {
  document.querySelectorAll('.node.is-selected').forEach(n => n.classList.remove('is-selected'));
  if (node) node.classList.add('is-selected');

  const name = formatName(person.given, person.patronymic, person.surname, person.maiden)
             || `Асоба #${person.id}`;
  document.getElementById('detail-name').textContent = name;

  const infoParts = [];
  if (person.birth) infoParts.push(`Нар.: ${formatDate(person.birth)}`);
  if (person.death) infoParts.push(`Пам.: ${formatDate(person.death)}`);
  if (person.place) infoParts.push(person.place);
  if (person.num != null) infoParts.push(`#${person.num}`);
  document.getElementById('detail-info').textContent = infoParts.join('  ·  ');

  const nav = document.getElementById('detail-nav');
  nav.innerHTML = '';
  if (person.id !== currentRootId) {
    const btn = document.createElement('button');
    btn.className = 'nav-btn';
    btn.textContent = 'Паказаць дрэва →';
    btn.addEventListener('click', () => navigate(person.id));
    nav.appendChild(btn);
  }

  document.getElementById('detail-panel').style.display = 'flex';
}

// ── Navigation ───────────────────────────────────────────────

function navigate(id) {
  document.getElementById('detail-panel').style.display = 'none';
  renderTree(buildTree(id));
}

function setMode(mode) {
  currentMode = mode;
  document.querySelectorAll('.mode-btn').forEach(b => {
    b.classList.toggle('mode-btn-active', b.dataset.mode === mode);
  });
  if (currentRootId) renderTree(buildTree(currentRootId));
}

function initUI() {
  document.getElementById('btn-home').addEventListener('click', () => navigate(CONFIG.homeId));

  // Mode buttons
  document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', () => setMode(btn.dataset.mode));
  });

  document.getElementById('detail-close').addEventListener('click', () => {
    document.getElementById('detail-panel').style.display = 'none';
    document.querySelectorAll('.node.is-selected').forEach(n => n.classList.remove('is-selected'));
  });

  window.addEventListener('hashchange', () => {
    const id = parseInt(location.hash.slice(1));
    if (id && id !== currentRootId) navigate(id);
  });
}

// ── Search ───────────────────────────────────────────────────

function initSearch() {
  const input   = document.getElementById('search-input');
  const results = document.getElementById('search-results');
  let debounce  = null;

  input.addEventListener('input', () => {
    clearTimeout(debounce);
    const raw = input.value.trim().toLowerCase();
    if (raw.length < 2) { results.style.display = 'none'; return; }

    debounce = setTimeout(() => {
      // Split query into words; every word must match somewhere in the name fields
      const words = raw.split(/\s+/).filter(Boolean);

      const matches = [];
      for (const r of SI) {
        const [id, sex, given, patronymic, surname, maiden, birthYear] = r;
        const fields = [given, patronymic, surname, maiden]
          .filter(Boolean)
          .map(s => s.toLowerCase());

        // Every query word must prefix-match at least one field token
        const allMatch = words.every(w =>
          fields.some(f => f.startsWith(w) || f.includes(w))
        );
        if (!allMatch) continue;

        // Score: prefer matches where more fields start with a query word
        const score = words.reduce((s, w) =>
          s + (fields.some(f => f.startsWith(w)) ? 1 : 0), 0
        );
        matches.push({ r, score });
        if (matches.length >= 50) break; // collect candidates then sort
      }

      // Sort: higher score first, then by birth year
      matches.sort((a, b) =>
        b.score - a.score || ((a.r[6] || 9999) - (b.r[6] || 9999))
      );

      results.innerHTML = '';
      if (!matches.length) { results.style.display = 'none'; return; }

      matches.slice(0, 10).forEach(({ r }) => {
        const [id, sex, given, patronymic, surname, maiden, birthYear] = r;
        const name = formatName(given, patronymic, surname, maiden) || `Асоба #${id}`;
        const div  = document.createElement('div');
        div.className = 'search-result';
        div.innerHTML = `
          <div class="search-result-name">${name}</div>
          <div class="search-result-sub">${surname || ''}${birthYear ? ' н.' + birthYear : ''} ${sex === 1 ? 'муж.' : 'жан.'}</div>
        `.trim();
        div.addEventListener('click', () => {
          results.style.display = 'none';
          input.value = '';
          navigate(id);
        });
        results.appendChild(div);
      });

      results.style.display = 'block';
    }, 250);
  });

  document.addEventListener('click', e => {
    if (!input.contains(e.target) && !results.contains(e.target)) {
      results.style.display = 'none';
    }
  });
}

// ── Descendant tree ──────────────────────────────────────────

const MAX_DESC_GENERATIONS = 6;

/**
 * Build a descendant node recursively.
 * Each node: { person, families: [{ spouse, children: [descNode] }] }
 */
function buildDescendantNode(id, depth, visited = new Set()) {
  if (!id || depth >= MAX_DESC_GENERATIONS) return null;
  if (visited.has(id)) return null;
  visited.add(id);
  const person = buildPerson(id);
  if (!person) return null;

  const rawFamilies = MA[id] || [];
  const families = rawFamilies.map(([spouseId, date, childIds]) => ({
    spouse:   buildPerson(spouseId),
    date,
    children: (childIds && childIds.length)
      ? childIds.map(cid => buildDescendantNode(cid, depth + 1, visited)).filter(Boolean)
      : [],
  }));

  // Cross-reference CH map — same logic as buildTree
  const allKnownChildren = new Set(families.flatMap(f => f.children.map(c => c.person.id)));
  const chChildren = (CH[id] || [])
    .filter(cid => !allKnownChildren.has(cid))
    .map(cid => buildDescendantNode(cid, depth + 1, visited))
    .filter(Boolean);

  if (chChildren.length) {
    families.push({ spouse: null, date: null, children: chChildren });
  }

  // Fallback: no marriage records at all
  if (!families.length) {
    const ch = (CH[id] || [])
      .map(cid => buildDescendantNode(cid, depth + 1, visited))
      .filter(Boolean);
    if (ch.length) families.push({ spouse: null, date: null, children: ch });
  }

  // Remove families with neither spouse nor children
  const validFamilies = families.filter(f => f.spouse || f.children.length);

  validFamilies.forEach(fam => {
    fam.children.sort((a, b) =>
      ((a.person.birth && a.person.birth[0]) || 9999) -
      ((b.person.birth && b.person.birth[0]) || 9999)
    );
  });

  return { person, families: validFamilies };
}

const DESC_SP_GAP  = 32;  // gap between person node and spouse node
const DESC_FAM_GAP = 40;  // gap between family blocks of the same person
const DESC_SIB_GAP = 20;  // minimum gap between child subtrees

/**
 * Width of one family block.
 * 
 * Layout per family block:
 *   [  couple  ][  children spread  ]
 *   but centred: anchor = midpoint of couple, children centred under anchor.
 *
 * The family slot must be wide enough that:
 *   - The couple fits (coupleW)
 *   - The children spread fits centred under the anchor
 *     anchor is at coupleW/2 from the left of the slot
 *     children need chW centred there:
 *       left child edge  = coupleW/2 - chW/2
 *       right child edge = coupleW/2 + chW/2
 *   So slot width = max(coupleW, coupleW/2 + chW/2) on right
 *                   and left overhang = max(0, chW/2 - coupleW/2)
 *   Total = left overhang + max(coupleW, coupleW/2 + chW/2)
 *         = max(coupleW, chW)  [when simplified]
 *
 * Wait — that simplifies to max(coupleW, chW). Let's verify:
 *   coupleW=200, chW=300: slot=300, anchor=100, children 100±150 → [-50, 250] ← extends left!
 *
 * The issue: anchor is at coupleW/2 but children need chW centred there.
 * If chW > coupleW, left half of children (chW/2) > coupleW/2, so they extend left.
 * 
 * Correct slot width = chW/2 + max(coupleW/2, chW/2)
 *                    = chW/2 + max(coupleW, chW)/2
 * No wait. Let slot_left=0.
 *   anchor = coupleW/2
 *   children go from (anchor - chW/2) to (anchor + chW/2)
 *   left edge of children = coupleW/2 - chW/2
 *   If chW > coupleW: left edge < 0 → need left padding = chW/2 - coupleW/2
 *   right edge = coupleW/2 + chW/2
 *   Slot = left_padding + right_edge
 *        = max(0, chW/2 - coupleW/2) + coupleW/2 + chW/2
 *        = max(coupleW/2, chW/2) + chW/2     [when chW>=coupleW]
 *   Simpler: slot = max(coupleW, chW) when chW <= coupleW (no overhang)
 *                   left_pad + coupleW/2 + chW/2 when chW > coupleW
 *
 * But this is getting complex. The SIMPLEST correct approach:
 * Centre the slot ON THE COUPLE MIDPOINT.
 * slot_width = max(coupleW, chW)
 * The person is at slot_centre - coupleW/2
 * The spouse is at slot_centre + coupleW/2 - NODE_W (if exists ... actually:)
 *   person_cx = slot_left + slot_w/2 - coupleW/2 + NODE_W/2
 *   anchor    = slot_left + slot_w/2  (centre of slot = anchor)
 *   spouse_cx = slot_left + slot_w/2 + coupleW/2 - NODE_W/2
 * Children centred at slot_left + slot_w/2. ✓ No overhangs!
 */
function descFamilySlotWidth(fam) {
  const chW = fam.children.length
    ? fam.children.reduce((s, c) => s + descSubtreeWidth(c), 0)
      + (fam.children.length - 1) * DESC_SIB_GAP
    : 0;
  if (fam.spouse) {
    const coupleW = NODE_W + DESC_SP_GAP + NODE_W;
    return Math.max(coupleW, chW);
  } else {
    return Math.max(NODE_W, chW);
  }
}

function descFamilyGap(famA, famB) {
  // Use a smaller gap between adjacent childless families
  // so spouses don't drift far from the person
  const aHasChildren = famA && famA.children.length > 0;
  const bHasChildren = famB && famB.children.length > 0;
  return (aHasChildren || bHasChildren) ? DESC_FAM_GAP : DESC_SP_GAP;
}

function descSubtreeWidth(node) {
  if (!node) return 0;
  if (!node.families.length) return NODE_W;
  let total = 0;
  node.families.forEach((fam, fi) => {
    total += descFamilySlotWidth(fam);
    if (fi < node.families.length - 1) {
      total += descFamilyGap(fam, node.families[fi + 1]);
    }
  });
  return Math.max(NODE_W, total);
}

/**
 * Assign cx positions top-down.
 * slotLeft = left edge of the slot allocated to this node.
 * The person's cx = slotLeft + slotW/2 adjusted per family layout.
 *
 * Since a person may have multiple families, each family gets its own sub-slot.
 * The person cx is at the centre of the FIRST family's sub-slot minus coupleW/2 + NODE_W/2.
 * But that's weird for multiple families — the person has one position.
 *
 * Better: person cx = left edge of first family slot + firstFamilySlotW/2 - coupleW/2 + NODE_W/2
 * For subsequent families, the anchor moves right but the person stays fixed.
 *
 * Layout for a node with N families, total slot width = subtreeWidth(node):
 *   family slots are placed left to right within the total slot, centred.
 *   Person cx = left edge of family[0] slot + family[0].slotW/2 - coupleW[0]/2 + NODE_W/2
 *   Spouse[i] cx = left edge of family[i] slot + family[i].slotW/2 + coupleW[i]/2 - NODE_W/2
 *   Anchor[i]    = left edge of family[i] slot + family[i].slotW/2
 *   Children[i] centred at Anchor[i]
 *
 * Person has ONE cx. For fi>0, the hline goes from personCx to spouse[fi].cx.
 * This means for fi>0 the couple is NOT centred in the sub-slot — the person
 * is to the left of the sub-slot. That's fine visually.
 */
function assignDescendantPositions(node, slotLeft, depth, results = []) {
  if (!node) return results;

  const famSlotWidths = node.families.length
    ? node.families.map(descFamilySlotWidth)
    : [NODE_W];
  let totalW = NODE_W;
  if (node.families.length) {
    totalW = famSlotWidths.reduce((s, w) => s + w, 0);
    node.families.forEach((fam, fi) => {
      if (fi < node.families.length - 1) totalW += descFamilyGap(fam, node.families[fi + 1]);
    });
  }

  // Place family sub-slots left-to-right, centred in the total slot
  // (slotLeft is the left edge of THIS node's total slot, width = descSubtreeWidth(node))
  const nodeSlotW = descSubtreeWidth(node);
  const famBlockStart = slotLeft + (nodeSlotW - totalW) / 2;

  let famLeft = famBlockStart;

  // Person cx: centre the person within the total slot allocated to this node.
  // This keeps the person's vertical stubs aligned with their family anchors
  // (avoids long horizontal connectors when a family has no spouse or when
  // the node has multiple families). The person is therefore centred in
  // the node's overall slot rather than biased to the first family.
  const personCx = slotLeft + nodeSlotW / 2;

  results.push({ node, cx: personCx, depth });

  node.families.forEach((fam, fi) => {
    const fsw         = famSlotWidths[fi];
    const slotCentre  = famLeft + fsw / 2;
    const coupleW     = fam.spouse ? NODE_W + DESC_SP_GAP + NODE_W : NODE_W;
    const spouseCx    = fam.spouse ? slotCentre + coupleW / 2 - NODE_W / 2 : null;
    // Anchor: always the slot centre (midpoint of couple when spouse, person centre when not)
    const anchorCx    = slotCentre;

    fam._anchorCx = anchorCx;
    fam._spouseCx = spouseCx;

    // Children centred at anchorCx
    if (fam.children.length) {
      const chWidths = fam.children.map(descSubtreeWidth);
      const chTotal  = chWidths.reduce((s, w) => s + w, 0)
        + (fam.children.length - 1) * DESC_SIB_GAP;
      let chLeft = anchorCx - chTotal / 2;
      fam.children.forEach((child, ci) => {
        assignDescendantPositions(child, chLeft, depth + 1, results);
        chLeft += chWidths[ci] + DESC_SIB_GAP;
      });
    }

    famLeft += fsw + (fi < node.families.length - 1 ? descFamilyGap(fam, node.families[fi + 1]) : 0);
  });

  return results;
}

function renderDescendants(svg, canvas, rootDescNode, slotLeft, startY) {
  const positions = assignDescendantPositions(rootDescNode, slotLeft, 0);
  const cxMap = new Map(positions.map(({ node, cx }) => [node.person.id, cx]));
  const placed = new Set();

  // Place all non-root person nodes
  positions.forEach(({ node, cx, depth }) => {
    if (depth === 0) return;
    if (placed.has(node.person.id)) return;
    placed.add(node.person.id);
    createAndAppend(node.person, cx, startY + depth * ROW_H, canvas);
  });

  // Draw spouses and connectors
  positions.forEach(({ node, cx: personCx, depth }) => {
    const y        = startY + depth * ROW_H;
    const hlineY   = y + Math.round(NODE_H / 2);
    const baseDrop = y + NODE_H + 36;

    node.families.forEach((fam, fi) => {
      if (fam.spouse && fam._spouseCx != null) {
        if (!placed.has(fam.spouse.id)) {
          placed.add(fam.spouse.id);
          createAndAppend(fam.spouse, fam._spouseCx, y, canvas);
        }
        drawLine(svg, personCx, hlineY, fam._spouseCx, hlineY, '#bbb', true);
      }

      if (fam.children.length && fam._anchorCx != null) {
        const dropY    = baseDrop - fi * 22;
        const childCxs = fam.children
          .map(c => cxMap.get(c.person.id))
          .filter(x => x != null);
        if (!childCxs.length) return;

        const stubX      = fam.spouse ? fam._anchorCx : personCx;
        const stubStartY = fam.spouse ? hlineY : nodeBot(y);
        const firstCx    = childCxs[0];
        const lastCx     = childCxs[childCxs.length - 1];

        // Vertical stub from person/anchor down to drop bar level
        drawLine(svg, stubX, stubStartY, stubX, dropY, '#7bc8a8');

        // Horizontal bar spanning only children
        if (childCxs.length > 1) drawBar(svg, firstCx, lastCx, dropY, '#7bc8a8');

        // Connect stub to children span if stub lands outside it
        if (stubX < firstCx) {
          drawLine(svg, stubX, dropY, firstCx, dropY, '#7bc8a8');
        } else if (stubX > lastCx) {
          drawLine(svg, lastCx, dropY, stubX, dropY, '#7bc8a8');
        }

        childCxs.forEach(chcx => {
          drawLine(svg, chcx, dropY, chcx, startY + (depth + 1) * ROW_H, '#7bc8a8');
        });
      }
    });
  });
}


function createAndAppend(person, cx, y, canvas) {
  const node = createNode(person, cx - NODE_W / 2, y);
  if (node) canvas.appendChild(node);
}