/**
 * tree.js — Veliatychi family tree visualiser
 *
 * Data is loaded from JSON files in data/ (generated by export.py).
 * Navigation is driven by URL hash: #<person_id>
 */

'use strict';

// ── Configuration ────────────────────────────────────────────
const CONFIG = {
  homeId:   11083,      // default person on first load — change to suit
  dataDir:  'data/',
  dataFiles: ['si', 'parents', 'children', 'marriages', 'places', 'nums', 'births', 'deaths'],
};

// ── Layout constants ─────────────────────────────────────────
const NODE_W   = 152;  // node width (px)
const NODE_H   = 88;   // node min-height (px) — used for spacing only
const GAP_X    = 20;   // horizontal gap between sibling nodes
const GAP_Y    = 80;   // vertical gap between generation rows
const ROW_H    = NODE_H + GAP_Y;
const SP_GAP   = 32;   // gap between root node edge and spouse node edge
const FAM_GAP  = 40;   // gap between children groups of different spouses
const STAGGER  = 22;   // vertical stagger between family drop bars (px)
const LABEL_W  = 90;   // left margin reserved for generation labels

// Derived row Y positions (relative to canvas top)
const Y_GGP  = 24;                    // great-grandparents
const Y_GP   = Y_GGP + ROW_H;        // grandparents
const Y_PAR  = Y_GP  + ROW_H;        // parents + root + spouses
const HLINE_Y    = Y_PAR + Math.round(NODE_H / 2);  // marriage line Y

// ── Global data store ─────────────────────────────────────────
// Populated by loadData(). Short names match JSON file names.
let SI; // search index: [[id, sex, given, patronymic, surname, maiden, birth_year], ...]
let PA; // parents:      {child_id: [father_id, mother_id]}
let CH; // children:     {parent_id: [child_id, ...]}
let MA; // marriages:    {person_id: [[spouse_id, [y,m,d], [child_ids]], ...]}
let PL; // places:       {person_id: "place name"}
let NU; // nums:         {person_id: integer}
let BI; // births:       {person_id: [y, m, d]}
let DE; // deaths:       {person_id: [y, m, d]}

let currentRootId = null;
let currentMode = 'ancestors';
let descendantGenerationLimit = null;

// ── Bootstrap ────────────────────────────────────────────────
(async function init() {
  await loadData();
  const startId = parseInt(location.hash.slice(1)) || CONFIG.homeId;
  renderTree(buildTree(startId));
  initSearch();
  initUI();
})();

// ── Data loading ─────────────────────────────────────────────
async function loadData() {
  const fill = document.getElementById('loading-fill');
  const msg  = document.getElementById('loading-msg');

  try {
    const results = {};
    for (let i = 0; i < CONFIG.dataFiles.length; i++) {
      const name = CONFIG.dataFiles[i];
      msg.textContent = `Загрузка ${name}…`;
      const resp = await fetch(CONFIG.dataDir + name + '.json');
      if (!resp.ok) throw new Error(`Failed to fetch ${name}.json (HTTP ${resp.status})`);
      results[name] = await resp.json();
      fill.style.width = Math.round((i + 1) / CONFIG.dataFiles.length * 100) + '%';
    }
    ({ si: SI, parents: PA, children: CH, marriages: MA,
       places: PL, nums: NU, births: BI, deaths: DE } = results);
    document.getElementById('loading').style.display = 'none';

  } catch (err) {
    document.getElementById('loading').style.display = 'none';
    document.getElementById('err-msg').textContent =
      err.message + '\n\nПераканайцеся, што файлы JSON знаходзяцца ў папцы data/. Запусціце export.py для іх стварэння.';
    document.getElementById('err').style.display = 'flex';
    throw err; // stop execution
  }
}

// ── Data helpers ─────────────────────────────────────────────

/** Format a [year, month, day] date tuple as dd.mm.yyyy */
function formatDate(d) {
  if (!d) return '?';
  const [y, m, dd] = d;
  if (!y)  return '?';
  if (!m)  return String(y);
  const pad = n => n ? String(n).padStart(2, '0') : '??';
  if (!dd) return `??.${pad(m)}.${y}`;
  return `${pad(dd)}.${pad(m)}.${y}`;
}

/** Build a display name: Surname (Maiden) Given Patronymic */
function formatName(given, patronymic, surname, maiden) {
  const surnamePart = surname
    ? (maiden && maiden !== surname ? `${surname} (${maiden})` : surname)
    : (maiden || null);
  return [surnamePart, given, patronymic].filter(Boolean).join(' ');
}

/** Build a person object from the data store */
/** Build a person object from the data store */
function buildPerson(id) {
  if (!id) return null;
  const r = SI.find(x => x[0] == id);
  if (!r && !BI[id] && !DE[id]) return null;
  return {
    id,
    sex:        r ? r[1] : 0,
    given:      r ? r[2] : null,
    patronymic: r ? r[3] : null,
    surname:    r ? r[4] : null,
    maiden:     r ? r[5] : null,
    birth:      BI[id] || null,
    death:      DE[id] || null,
    place:      PL[id] || null,
    num:        NU[id] ?? null,
  };
}

/**
 * Recursively build an ancestor subtree node.
 * Each node: { person, father, mother } (father/mother are ancestor nodes or null).
 */
function buildAncestorNode(id, seen = new Set()) {
  if (!id) return null;
  const key = String(id);
  if (seen.has(key)) return null;
  const person = buildPerson(id);
  if (!person) return null;
  const nextSeen = new Set(seen);
  nextSeen.add(key);
  const [fatherId, motherId] = PA[id] || [null, null];
  return {
    person,
    father: buildAncestorNode(fatherId, nextSeen),
    mother: buildAncestorNode(motherId, nextSeen),
  };
}

/** Compute subtree extents from a person's centre. */
function ancestorExtents(node) {
  if (!node) return { left: 0, right: 0 };
  const self = NODE_W / 2;
  const fatherExt = ancestorExtents(node.father);
  const motherExt = ancestorExtents(node.mother);

  if (node.father && node.mother) {
    const parentOffset = (fatherExt.right + GAP_X + motherExt.left) / 2;
    return {
      left: Math.max(self, parentOffset + fatherExt.left),
      right: Math.max(self, parentOffset + motherExt.right),
    };
  }

  if (node.father) {
    return {
      left: Math.max(self, fatherExt.left),
      right: Math.max(self, fatherExt.right),
    };
  }

  if (node.mother) {
    return {
      left: Math.max(self, motherExt.left),
      right: Math.max(self, motherExt.right),
    };
  }

  return { left: self, right: self };
}

/**
 * Assign cx (horizontal centre) to every ancestor node, top-down.
 * Returns flat array of { person, cx, depth } for all ancestors.
 * depth=0 is the root, depth=1 is parents, etc.
 */
function assignAncestorPositions(node, cx, depth, results = []) {
  if (!node) return results;
  results.push({ node, person: node.person, cx, depth });
  if (node.father && node.mother) {
    const fatherExt = ancestorExtents(node.father);
    const motherExt = ancestorExtents(node.mother);
    const parentOffset = (fatherExt.right + GAP_X + motherExt.left) / 2;
    assignAncestorPositions(node.father, cx - parentOffset, depth + 1, results);
    assignAncestorPositions(node.mother, cx + parentOffset, depth + 1, results);
  } else if (node.father) {
    assignAncestorPositions(node.father, cx, depth + 1, results);
  } else if (node.mother) {
    assignAncestorPositions(node.mother, cx, depth + 1, results);
  }
  return results;
}

function buildAncestorGraphLayout(ancestorTree, rootCx) {
  const occurrences = assignAncestorPositions(ancestorTree, rootCx, 0);
  const nodesById = new Map();
  const edgeKeys = new Set();
  const edges = [];

  occurrences.forEach(pos => {
    const id = String(pos.person.id);
    const existing = nodesById.get(id);
    if (!existing) {
      nodesById.set(id, {
        person: pos.person,
        depth: pos.depth,
        occurrencePositions: [pos],
      });
    } else {
      existing.depth = Math.max(existing.depth, pos.depth);
      existing.occurrencePositions.push(pos);
    }
  });

  occurrences.forEach(pos => {
    [
      ['father', pos.node.father],
      ['mother', pos.node.mother],
    ].forEach(([kind, parentNode]) => {
      if (!parentNode) return;
      const key = `${parentNode.person.id}:${pos.person.id}:${kind}`;
      if (edgeKeys.has(key)) return;
      edgeKeys.add(key);
      edges.push({
        kind,
        parentId: String(parentNode.person.id),
        childId: String(pos.person.id),
      });
    });
  });

  const nodes = Array.from(nodesById.entries()).map(([id, node]) => {
    const deepest = node.occurrencePositions.filter(pos => pos.depth === node.depth);
    const cx = deepest.reduce((sum, pos) => sum + pos.cx, 0) / deepest.length;
    return { id, person: node.person, depth: node.depth, cx };
  });

  const rows = new Map();
  nodes.forEach(node => {
    if (!rows.has(node.depth)) rows.set(node.depth, []);
    rows.get(node.depth).push(node);
  });

  rows.forEach(row => {
    row.sort((a, b) => a.cx - b.cx || Number(a.id) - Number(b.id));
    for (let i = 1; i < row.length; i += 1) {
      const minCx = row[i - 1].cx + NODE_W + GAP_X;
      if (row[i].cx < minCx) row[i].cx = minCx;
    }
  });

  return { nodes, edges };
}

/** Build the full tree data structure centred on rootId. */
function buildTree(rootId) {
  const root = buildPerson(rootId);
  if (!root) return null;

  const [fatherId, motherId] = PA[rootId] || [null, null];
  const ancestorTree = {
    person: root,
    father: buildAncestorNode(fatherId, new Set([String(rootId)])),
    mother: buildAncestorNode(motherId, new Set([String(rootId)])),
  };

  const families = (MA[rootId] || []).map(([spouseId, marriageDate, childIds]) => {
    // childIds from MA is the per-couple list; fall back to all children if empty
    const children = (childIds && childIds.length)
      ? childIds.map(buildPerson).filter(Boolean)
      : [];
    return {
      spouse:   buildPerson(spouseId),
      date:     marriageDate,
      children,
    };
  });

  // Fallback: no marriage records at all — use CH map
  if (!families.length) {
    const ch = (CH[rootId] || []).map(buildPerson).filter(Boolean);
    if (ch.length) families.push({ spouse: null, date: null, children: ch });
  }

  // Any children not accounted for in MA get their own anonymous family
  const allKnownChildren = new Set(families.flatMap(f => f.children.map(c => c.id)));
  const chChildren = (CH[rootId] || []).map(buildPerson).filter(Boolean);
  const unknownChildren = chChildren.filter(c => !allKnownChildren.has(c.id));
  if (unknownChildren.length) {
    families.push({ spouse: null, date: null, children: unknownChildren });
  }

  // Remove families that have neither spouse nor children (nothing to show)
  const validFamilies = families.filter(f => f.spouse || f.children.length);

  validFamilies.forEach(fam => {
    fam.children.sort((a, b) =>
      ((a.birth && a.birth[0]) || 9999) - ((b.birth && b.birth[0]) || 9999)
    );
  });

  return { ancestorTree, families: validFamilies };
}

function birthYear(person) {
  if (!person) return 9999;
  if (person.birth && person.birth[0]) return person.birth[0];
  const r = SI.find(x => x[0] == person.id);
  return (r && r[6]) || 9999;
}

function buildFamilyGroups(personId) {
  const families = (MA[personId] || []).map(([spouseId, marriageDate, childIds]) => {
    const children = (childIds && childIds.length)
      ? childIds.map(buildPerson).filter(Boolean)
      : [];
    return {
      spouse: buildPerson(spouseId),
      date: marriageDate,
      children,
    };
  });

  if (!families.length) {
    const ch = (CH[personId] || []).map(buildPerson).filter(Boolean);
    if (ch.length) families.push({ spouse: null, date: null, children: ch });
  }

  const allKnownChildren = new Set(families.flatMap(f => f.children.map(c => c.id)));
  const chChildren = (CH[personId] || []).map(buildPerson).filter(Boolean);
  const unknownChildren = chChildren.filter(c => !allKnownChildren.has(c.id));
  if (unknownChildren.length) {
    families.push({ spouse: null, date: null, children: unknownChildren });
  }

  const validFamilies = families.filter(f => f.spouse || f.children.length);
  validFamilies.forEach(fam => {
    fam.children.sort((a, b) => birthYear(a) - birthYear(b));
  });

  return validFamilies;
}

const descendantLayout = DescendantLayout.create({
  nodeWidth: NODE_W,
  gapX: GAP_X,
  spouseGap: SP_GAP,
  familyGap: FAM_GAP,
  stagger: STAGGER,
  birthYear,
  getFamilies: buildFamilyGroups,
  treeLayout: TreeLayout,
});

function resolveDescendantGenerationLimit() {
  return descendantGenerationLimit == null ? Infinity : Math.max(1, descendantGenerationLimit);
}

function computeDescendantDepth(personId, maxDepth = Infinity) {
  return descendantLayout.computeDepth(personId, maxDepth);
}

function computeDescendantLayout(personId, remainingGenerations = Infinity) {
  return descendantLayout.computeLayout(personId, remainingGenerations);
}

function computeDescendantWidth(personId) {
  return computeDescendantLayout(personId, resolveDescendantGenerationLimit()).width;
}

// ── Layout helpers ───────────────────────────────────────────

/** X centre of a node placed at left edge x */
const nodeCx = x => x + NODE_W / 2;

/** Y bottom of a node placed at top edge y */
const nodeBot = y => y + NODE_H;

// ── SVG helpers ──────────────────────────────────────────────

function svgEl(tag, attrs) {
  const el = document.createElementNS('http://www.w3.org/2000/svg', tag);
  for (const [k, v] of Object.entries(attrs)) el.setAttribute(k, v);
  return el;
}

function drawLine(svg, x1, y1, x2, y2, stroke, dashed = false, strokeWidth = 1.5) {
  const attrs = { x1, y1, x2, y2, stroke, 'stroke-width': strokeWidth };
  if (dashed) attrs['stroke-dasharray'] = '5,4';
  svg.appendChild(svgEl('line', attrs));
}

function drawCasedLine(svg, x1, y1, x2, y2, stroke, dashed = false) {
  drawLine(svg, x1, y1, x2, y2, '#fff', dashed, 5);
  drawLine(svg, x1, y1, x2, y2, stroke, dashed, 1.5);
}

function drawBar(svg, cx1, cx2, y, stroke) {
  drawLine(svg, Math.min(cx1, cx2), y, Math.max(cx1, cx2), y, stroke);
}

// ── Node DOM helpers ─────────────────────────────────────────

function createNode(person, x, y, isRoot = false) {
  if (!person) return null;
  const name = formatName(person.given, person.patronymic, person.surname, person.maiden)
             || `Асоба #${person.id}`;
  const dates = (person.birth || person.death)
    ? `${formatDate(person.birth)} — ${formatDate(person.death)}` : '';
  const div = document.createElement('div');
  div.className = ['node',
    person.sex === 1 ? 'sex-m' : person.sex === 2 ? 'sex-f' : '',
    isRoot ? 'is-root' : ''].filter(Boolean).join(' ');
  div.style.cssText = `left:${x}px;top:${y}px`;
  div.dataset.id = person.id;
  div.innerHTML = [
    `<div class="node-name">${name}</div>`,
    dates        ? `<div class="node-dates">${dates}</div>` : '',
    person.place ? `<div class="node-place">${person.place}</div>` : '',
    person.num != null ? `<span class="node-num">#${person.num}</span>` : '',
  ].join('');
  div.addEventListener('click', () => showDetailPanel(person, div));
  return div;
}

// ── Render ───────────────────────────────────────────────────

function renderTree(tree) {
  if (!tree) return;

  const canvas = document.getElementById('canvas');
  canvas.innerHTML = '';

  const { ancestorTree, families } = tree;
  const visualFamilies = currentMode === 'descendants'
    ? descendantLayout.orderFamilies(families)
    : families;

  // ── Ancestor depth & Y_ROOT ───────────────────────────────
  const actualDepth = (function maxDepth(node) {
    if (!node) return 0;
    return 1 + Math.max(maxDepth(node.father), maxDepth(node.mother));
  })(ancestorTree) - 1;

  const Y_ROOT      = 24 + actualDepth * ROW_H;
  const HLINE_Y     = Y_ROOT + Math.round(NODE_H / 2);

  // ── Spouse layout offsets ─────────────────────────────────
  const MARGIN  = 20;
  const {
    orderedFams,
    leftFams,
    rightFams,
    leftSpouseOffsets,
    rightSpouseOffsets,
  } = descendantLayout.splitFamilies(visualFamilies);

  // ── Compute below-root width ───────────────────────────────
  const descendantLimit = resolveDescendantGenerationLimit();
  const belowLayout = currentMode === 'descendants'
    ? computeDescendantLayout(ancestorTree.person.id, descendantLimit)
    : null;
  const belowLeftNeeded = belowLayout ? belowLayout.rootOffset : 0;
  const belowRightNeeded = belowLayout ? belowLayout.width - belowLayout.rootOffset : 0;

  // ── Resolve rootCx ────────────────────────────────────────
  const leftSpouseNeeded = leftSpouseOffsets.length
    ? -(leftSpouseOffsets[leftSpouseOffsets.length-1] - NODE_W/2) : 0;
  const ancestorBounds = ancestorExtents(ancestorTree);

  const rootCxRaw = Math.max(
    MARGIN + leftSpouseNeeded,
    MARGIN + belowLeftNeeded,
    MARGIN + ancestorBounds.left,
  );

  const ancestorPositions = assignAncestorPositions(ancestorTree, rootCxRaw, 0);
  const minAncCx = ancestorPositions.reduce((m, p) => Math.min(m, p.cx), rootCxRaw);
  const shift    = Math.max(0, MARGIN + NODE_W/2 - minAncCx);
  const rootCx   = rootCxRaw + shift;

  const ancestorGraph = currentMode === 'ancestors'
    ? buildAncestorGraphLayout(ancestorTree, rootCx)
    : null;
  const positions = ancestorGraph
    ? ancestorGraph.nodes
    : assignAncestorPositions(ancestorTree, rootCx, 0);
  const posByNode = ancestorGraph
    ? null
    : new Map(positions.map(p => [p.node, p]));
  const posById = ancestorGraph
    ? new Map(positions.map(p => [p.id, p]))
    : null;

  // ── Canvas size ───────────────────────────────────────────
  const rightSpouseNeeded = rightSpouseOffsets.length
    ? rightSpouseOffsets[rightSpouseOffsets.length-1] + NODE_W/2 : NODE_W/2;
  const maxAncCx = positions.reduce((m, p) => Math.max(m, p.cx), rootCx);

  const canvasW = Math.ceil(Math.max(
    maxAncCx + NODE_W/2 + MARGIN,
    rootCx + rightSpouseNeeded + MARGIN,
    rootCx + belowRightNeeded + MARGIN,
  ));
  const descendantDepth = currentMode === 'descendants'
    ? computeDescendantDepth(ancestorTree.person.id, descendantLimit)
    : 0;
  const canvasH = Y_ROOT
    + (descendantDepth + 1) * ROW_H
    + 40;

  canvas.style.cssText = `width:${canvasW}px;height:${canvasH}px;position:relative`;
  const svg = svgEl('svg', { class: 'connectors', style: `width:${canvasW}px;height:${canvasH}px` });
  canvas.appendChild(svg);

  function placeNode(person, cx, y, isRoot = false) {
    const node = createNode(person, cx - NODE_W/2, y, isRoot);
    if (node) canvas.appendChild(node);
  }

  // ── Place ancestor nodes ──────────────────────────────────
  positions.forEach(({ person, cx, depth }) => {
    placeNode(person, cx, Y_ROOT - depth * ROW_H, depth === 0);
  });

  // ── Ancestor connectors ───────────────────────────────────
  if (ancestorGraph) {
    const edgesByChild = new Map();
    ancestorGraph.edges.forEach(edge => {
      if (!edgesByChild.has(edge.childId)) edgesByChild.set(edge.childId, []);
      edgesByChild.get(edge.childId).push(edge);
    });

    edgesByChild.forEach((edges, childId) => {
      const childPos = posById.get(childId);
      if (!childPos) return;
      const childY = Y_ROOT - childPos.depth * ROW_H;
      const fatherEdge = edges.find(edge => edge.kind === 'father');
      const motherEdge = edges.find(edge => edge.kind === 'mother');
      const fpos = fatherEdge ? posById.get(fatherEdge.parentId) : null;
      const mpos = motherEdge ? posById.get(motherEdge.parentId) : null;

      if (fpos && mpos) {
        const fatherY = Y_ROOT - fpos.depth * ROW_H;
        const motherY = Y_ROOT - mpos.depth * ROW_H;
        const coupleY = Math.min(
          childY - 8,
          Math.max(nodeBot(fatherY), nodeBot(motherY)) + Math.round(GAP_Y * 0.5)
        );
        const barMid = (fpos.cx + mpos.cx) / 2;

        drawCasedLine(svg, fpos.cx, nodeBot(fatherY), fpos.cx, coupleY, '#7ca8d8');
        drawCasedLine(svg, mpos.cx, nodeBot(motherY), mpos.cx, coupleY, '#d87898');
        drawCasedLine(svg, fpos.cx, coupleY, mpos.cx, coupleY, '#aaa');
        if (Math.abs(barMid - childPos.cx) > 0.5) {
          const branchY = Math.min(childY - 8, coupleY + 16);
          drawCasedLine(svg, barMid, coupleY, barMid, branchY, '#999');
          drawCasedLine(svg, barMid, branchY, childPos.cx, branchY, '#999');
          drawCasedLine(svg, childPos.cx, branchY, childPos.cx, childY, '#999');
        } else {
          drawCasedLine(svg, childPos.cx, coupleY, childPos.cx, childY, '#999');
        }
      } else {
        const parentPos = fpos || mpos;
        if (!parentPos) return;
        const parentY = Y_ROOT - parentPos.depth * ROW_H;
        const color = fpos ? '#7ca8d8' : '#d87898';
        const elbowY = Math.min(childY - 8, nodeBot(parentY) + Math.round(GAP_Y * 0.5));

        drawCasedLine(svg, parentPos.cx, nodeBot(parentY), parentPos.cx, elbowY, color);
        if (Math.abs(parentPos.cx - childPos.cx) > 0.5) {
          drawCasedLine(svg, parentPos.cx, elbowY, childPos.cx, elbowY, color);
        }
        drawCasedLine(svg, childPos.cx, elbowY, childPos.cx, childY, color);
      }
    });
  } else {
    positions.forEach(({ node, person, cx, depth }) => {
      const childY  = Y_ROOT - depth * ROW_H;
      const parentY = Y_ROOT - (depth + 1) * ROW_H;
      const midY    = nodeBot(parentY) + Math.round(GAP_Y * 0.5);
      const fpos = node.father ? posByNode.get(node.father) : null;
      const mpos = node.mother ? posByNode.get(node.mother) : null;
      if (!fpos && !mpos) return;
      if (fpos && mpos) {
        drawLine(svg, fpos.cx, nodeBot(parentY), fpos.cx, midY, '#7ca8d8');
        drawLine(svg, mpos.cx, nodeBot(parentY), mpos.cx, midY, '#d87898');
        const barMid = (fpos.cx + mpos.cx) / 2;
        if (Math.abs(barMid - cx) > 0.5) {
          const parentLeft = Math.min(fpos.cx, mpos.cx);
          const parentRight = Math.max(fpos.cx, mpos.cx);
          const offsetLeft = Math.min(barMid, cx);
          const offsetRight = Math.max(barMid, cx);

          if (parentLeft < offsetLeft) drawBar(svg, parentLeft, offsetLeft, midY, '#aaa');
          if (offsetRight < parentRight) drawBar(svg, offsetRight, parentRight, midY, '#aaa');
          drawLine(svg, barMid, midY, cx, midY, '#999');
        } else {
          drawBar(svg, fpos.cx, mpos.cx, midY, '#aaa');
          drawLine(svg, cx, midY, cx, childY, '#999');
        }
        if (Math.abs(barMid - cx) > 0.5) drawLine(svg, cx, midY, cx, childY, '#999');
      } else {
        const parentCx = fpos ? fpos.cx : mpos.cx;
        const color    = fpos ? '#7ca8d8' : '#d87898';
        drawLine(svg, parentCx, nodeBot(parentY), parentCx, childY, color);
      }
    });
  }

  // ── Spouses + marriage hlines ─────────────────────────────
  const leftSpouseCx  = leftSpouseOffsets.map(o  => rootCx + o);
  const rightSpouseCx = rightSpouseOffsets.map(o => rootCx + o);
  leftFams.forEach((fam, i) => {
    const scx    = leftSpouseCx[i];
    const fromCx = i === 0 ? rootCx : leftSpouseCx[i-1];
    if (fam.spouse) {
      placeNode(fam.spouse, scx, Y_ROOT);
      drawLine(svg, scx, HLINE_Y, fromCx, HLINE_Y, '#bbb', true);
    }
  });
  rightFams.forEach((fam, i) => {
    const scx    = rightSpouseCx[i];
    const fromCx = i === 0 ? rootCx : rightSpouseCx[i-1];
    if (fam.spouse) {
      placeNode(fam.spouse, scx, Y_ROOT);
      drawLine(svg, fromCx, HLINE_Y, scx, HLINE_Y, '#bbb', true);
    }
  });

  // ── Below root: draw descendants ───────────────────────────
  if (currentMode === 'descendants') {
    renderDescendants(svg, ancestorTree, rootCx, Y_ROOT, orderedFams, MARGIN, descendantLimit);
  }

function renderDescendants(svg, ancestorTree, rootCx, Y_ROOT, orderedFams, MARGIN, maxGenerations) {
  if (maxGenerations <= 0) return;
  const rootFamilies = orderedFams.filter(Boolean);
  let depth = 1;
  let queue = renderDescendantParent(svg, ancestorTree.person, rootCx, Y_ROOT, rootFamilies, false, MARGIN, maxGenerations);

  while (queue.length && depth < maxGenerations) {
    depth += 1;
    const nextQueue = [];
    for (const { person, cx, y } of queue) {
      const families = buildFamilyGroups(person.id).filter(Boolean);
      if (!families.length) continue;
      const remainingGenerations = maxGenerations - depth + 1;
      nextQueue.push(...renderDescendantParent(svg, person, cx, y, families, true, MARGIN, remainingGenerations));
    }
    queue = nextQueue;
  }
}

function renderDescendantParent(svg, parent, parentCx, parentY, families, renderSpouses, MARGIN, remainingGenerations) {
  if (!(families || []).length || remainingGenerations <= 0) return [];

  const Y_CH = parentY + ROW_H;
  const baseDropY = parentY + ROW_H - 16;
  const familyLayout = descendantLayout.positionChildFamilyBlocks(parentCx, families, remainingGenerations, MARGIN);
  const { leftFams, rightFams, leftSpouseOffsets, rightSpouseOffsets, positionedBlocks } = familyLayout;

  if (renderSpouses) {
    leftFams.forEach((fam, i) => {
      const scx = parentCx + leftSpouseOffsets[i];
      const fromCx = i === 0 ? parentCx : parentCx + leftSpouseOffsets[i - 1];
      if (fam.spouse) {
        placeNode(fam.spouse, scx, parentY);
        const hlineY = parentY + Math.round(NODE_H / 2);
        drawLine(svg, scx, hlineY, fromCx, hlineY, '#bbb', true);
      }
    });
    rightFams.forEach((fam, i) => {
      const scx = parentCx + rightSpouseOffsets[i];
      const fromCx = i === 0 ? parentCx : parentCx + rightSpouseOffsets[i - 1];
      if (fam.spouse) {
        placeNode(fam.spouse, scx, parentY);
        const hlineY = parentY + Math.round(NODE_H / 2);
        drawLine(svg, fromCx, hlineY, scx, hlineY, '#bbb', true);
      }
    });
  }

  const drawnAnchors = new Set();
  const childPositions = [];
  positionedBlocks.forEach(blk => {
    blk.stubStartY = blk.fam.spouse ? parentY + Math.round(NODE_H / 2) : nodeBot(parentY);
  });

  const effectiveLaneGap = descendantLayout.connectorLaneGap(positionedBlocks, baseDropY);

  positionedBlocks.forEach((blk) => {
    const familyDropY = Math.max(blk.stubStartY + 8, baseDropY - blk.connectorLane * effectiveLaneGap);
    const key = `${blk.anchorCx},${blk.stubStartY},${familyDropY}`;

    if (!drawnAnchors.has(key)) {
      drawnAnchors.add(key);
      drawLine(svg, blk.anchorCx, blk.stubStartY, blk.anchorCx, familyDropY, '#7bc8a8');
    }

    if (blk.children.length > 1) drawBar(svg, blk.firstCx, blk.lastCx, familyDropY, '#7bc8a8');
    if (blk.anchorCx < blk.firstCx) drawLine(svg, blk.anchorCx, familyDropY, blk.firstCx, familyDropY, '#7bc8a8');
    else if (blk.anchorCx > blk.lastCx) drawLine(svg, blk.lastCx, familyDropY, blk.anchorCx, familyDropY, '#7bc8a8');

    let childCursor = blk.childBlockLeft;
    blk.children.forEach((child, ci) => {
      const childLayout = blk.childLayouts[ci];
      const childCx = childCursor + childLayout.rootOffset;
      placeNode(child, childCx, Y_CH);
      drawLine(svg, childCx, familyDropY, childCx, Y_CH, '#7bc8a8');
      childPositions.push({ person: child, cx: childCx, y: Y_CH });
      childCursor += childLayout.width + GAP_X;
    });
  });

  return childPositions;
}

  // ── Update state ──────────────────────────────────────────
  currentRootId = ancestorTree.person.id;
  document.getElementById('crumb').textContent =
    formatName(ancestorTree.person.given, ancestorTree.person.patronymic,
               ancestorTree.person.surname, ancestorTree.person.maiden);
  updateDescendantLimitControl(currentRootId);

  const newHash = `#${currentRootId}`;
  if (location.hash !== newHash) history.replaceState(null, '', newHash);

  // Centre root in viewport
  {
    const toolbar = document.getElementById('toolbar');
    const vw = window.innerWidth;
    const vh = window.innerHeight - (toolbar ? toolbar.offsetHeight : 48);
    const targetX = Math.round(vw / 2);
    const targetY = Math.round(vh / 3);
    const padLeft = Math.max(0, targetX - rootCx);
    const padTop  = Math.max(0, targetY - Y_ROOT);
    canvas.style.cssText += `;margin-left:${padLeft}px;margin-top:${padTop}px`;
    const wrap = document.getElementById('canvas-wrap');
    wrap.scrollLeft = Math.max(0, rootCx + padLeft - targetX);
    wrap.scrollTop  = Math.max(0, Y_ROOT + padTop  - targetY);
  }
}

// ── Detail panel ─────────────────────────────────────────────

function showDetailPanel(person, node) {
  document.querySelectorAll('.node.is-selected').forEach(n => n.classList.remove('is-selected'));
  if (node) node.classList.add('is-selected');

  const name = formatName(person.given, person.patronymic, person.surname, person.maiden)
             || `Асоба #${person.id}`;
  document.getElementById('detail-name').textContent = name;

  const infoParts = [];
  if (person.birth) infoParts.push(`Нар.: ${formatDate(person.birth)}`);
  if (person.death) infoParts.push(`Пам.: ${formatDate(person.death)}`);
  if (person.place) infoParts.push(person.place);
  if (person.num != null) infoParts.push(`#${person.num}`);
  document.getElementById('detail-info').textContent = infoParts.join('  ·  ');

  const nav = document.getElementById('detail-nav');
  nav.innerHTML = '';
  if (person.id !== currentRootId) {
    const btn = document.createElement('button');
    btn.className = 'nav-btn';
    btn.textContent = 'Паказаць дрэва →';
    btn.addEventListener('click', () => navigate(person.id));
    nav.appendChild(btn);
  }

  document.getElementById('detail-panel').style.display = 'flex';
}

// ── Navigation ───────────────────────────────────────────────

function navigate(id) {
  document.getElementById('detail-panel').style.display = 'none';
  renderTree(buildTree(id));
}

function updateDescendantLimitControl(rootId) {
  const control = document.getElementById('descendant-limit-control');
  const options = document.getElementById('descendant-limit-options');
  if (!control || !options) return;

  control.style.display = currentMode === 'descendants' ? 'flex' : 'none';

  const maxDepth = computeDescendantDepth(rootId);
  const nextValue = descendantGenerationLimit == null || maxDepth <= 0 || descendantGenerationLimit >= maxDepth
    ? 'all'
    : String(descendantGenerationLimit);

  options.innerHTML = '';

  function addLimitButton(value, label) {
    const button = document.createElement('button');
    button.type = 'button';
    button.className = [
      'generation-limit-btn',
      value === nextValue ? 'generation-limit-btn-active' : '',
    ].filter(Boolean).join(' ');
    button.dataset.limit = value;
    button.textContent = label;
    button.setAttribute('aria-pressed', value === nextValue ? 'true' : 'false');
    button.addEventListener('click', () => {
      descendantGenerationLimit = value === 'all' ? null : Number(value);
      if (currentRootId) renderTree(buildTree(currentRootId));
    });
    options.appendChild(button);
  }

  addLimitButton('all', 'Усе');

  for (let generation = 1; generation < maxDepth; generation += 1) {
    addLimitButton(String(generation), String(generation));
  }

  descendantGenerationLimit = nextValue === 'all' ? null : Number(nextValue);
}

function setMode(mode) {
  currentMode = mode;
  document.querySelectorAll('.mode-btn').forEach(b => {
    b.classList.toggle('mode-btn-active', b.dataset.mode === mode);
  });
  if (currentRootId) updateDescendantLimitControl(currentRootId);
  if (currentRootId) renderTree(buildTree(currentRootId));
}

function initUI() {
  document.getElementById('btn-home').addEventListener('click', () => navigate(CONFIG.homeId));

  // Mode buttons
  document.querySelectorAll('.mode-btn').forEach(btn => {
    btn.addEventListener('click', () => setMode(btn.dataset.mode));
  });

  document.getElementById('detail-close').addEventListener('click', () => {
    document.getElementById('detail-panel').style.display = 'none';
    document.querySelectorAll('.node.is-selected').forEach(n => n.classList.remove('is-selected'));
  });

  window.addEventListener('hashchange', () => {
    const id = parseInt(location.hash.slice(1));
    if (id && id !== currentRootId) navigate(id);
  });
}

// ── Search ───────────────────────────────────────────────────

function initSearch() {
  const input   = document.getElementById('search-input');
  const results = document.getElementById('search-results');
  let debounce  = null;

  input.addEventListener('input', () => {
    clearTimeout(debounce);
    const raw = input.value.trim().toLowerCase();
    if (raw.length < 2) { results.style.display = 'none'; return; }

    debounce = setTimeout(() => {
      // Split query into words; every word must match somewhere in the name fields
      const words = raw.split(/\s+/).filter(Boolean);

      const matches = [];
      for (const r of SI) {
        const [id, sex, given, patronymic, surname, maiden, birthYear] = r;
        const fields = [given, patronymic, surname, maiden]
          .filter(Boolean)
          .map(s => s.toLowerCase());

        // Every query word must prefix-match at least one field token
        const allMatch = words.every(w =>
          fields.some(f => f.startsWith(w) || f.includes(w))
        );
        if (!allMatch) continue;

        // Score: prefer matches where more fields start with a query word
        const score = words.reduce((s, w) =>
          s + (fields.some(f => f.startsWith(w)) ? 1 : 0), 0
        );
        matches.push({ r, score });
        if (matches.length >= 50) break; // collect candidates then sort
      }

      // Sort: higher score first, then by birth year
      matches.sort((a, b) =>
        b.score - a.score || ((a.r[6] || 9999) - (b.r[6] || 9999))
      );

      results.innerHTML = '';
      if (!matches.length) { results.style.display = 'none'; return; }

      matches.slice(0, 10).forEach(({ r }) => {
        const [id, sex, given, patronymic, surname, maiden, birthYear] = r;
        const name = formatName(given, patronymic, surname, maiden) || `Асоба #${id}`;
        const div  = document.createElement('div');
        div.className = 'search-result';
        div.innerHTML = `
          <div class="search-result-name">${name}</div>
          <div class="search-result-sub">${surname || ''}${birthYear ? ' н.' + birthYear : ''} ${sex === 1 ? 'муж.' : 'жан.'}</div>
        `.trim();
        div.addEventListener('click', () => {
          results.style.display = 'none';
          input.value = '';
          navigate(id);
        });
        results.appendChild(div);
      });

      results.style.display = 'block';
    }, 250);
  });

  document.addEventListener('click', e => {
    if (!input.contains(e.target) && !results.contains(e.target)) {
      results.style.display = 'none';
    }
  });
}

